### PR TITLE
docs: update navbar

### PR DESCRIPTION
**Pull request by huynhicode**
## :bookmark_tabs: Summary

This PR updates the navigation bar for a more intuitive user experience.

- `Intro` has been renamed to `Docs`
- `Configuration` has been renamed to `Tutorials`
- `Syntax` has been removed
- `Misc` has been renamed to `Integrations`
- `Community` has been removed

Added:
- `Slack`
- `GitHub`

---

**Screenshots:**

Screen Shot 2022-12-11 at 6 42 19 PM

Screen Shot 2022-12-11 at 7 03 05 PM

Resolves #<your issue id here>

none

## :straight_ruler: Design Decisions

Describe the way your implementation works or what design decisions you made if applicable.

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [ ] :computer: have added unit/e2e tests (if appropriate)
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by sidharthv96** [comment]
> Configuration has been renamed to Tutorials

The conflict is based on this. 

Should we make the slack and github as icons?

**Comment by huynhicode** [comment]
Great suggestion @sidharthv96 !  I will convert the text to icons for Slack and GitHub.

And will resolve the conflicts.

**Comment by huynhicode** [comment]
Updated navbar screenshot:

Screen Shot 2022-12-19 at 7 57 06 PM

Vitepress allows for social media icons to be added to the navbar in `themeConfig`:

https://vitepress.vuejs.org/config/theme-configs#sociallinks

Screen Shot 2022-12-19 at 8 01 04 PM

**Comment by sidharthv96** [comment]
@huynhicode, thank you!

**Pull request merged**
