### PR TITLE
Bar chart (using gantt chart)

### PR DESCRIPTION
**Pull request by karistom**
## :bookmark_tabs: Summary

updated README.md with example of Bar chart (using gantt chart) 
Bar chart feature is not available yet, issue https://github.com/mermaid-js/mermaid/issues/2352 is still open.
This example can be used as workaround for now.

Workaround of [#<your issue id here>](https://github.com/mermaid-js/mermaid/issues/2352)

## :straight_ruler: Design Decisions

Showing Bar chart using gantt chart feature
image

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added unit/e2e tests (if appropriate)
- [x] :notebook: have added documentation (if appropriate)
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by karistom** [comment]
@knsv @sidharthv96

**Comment by sidharthv96** [comment]
@karistom can you please add it to the example at https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/syntax/gantt.md too?

**Comment by karistom** [comment]
@sidharthv96 I updated the example.

**Comment by karistom** [comment]
@sidharthv96 the change has been applied. please review it again.

**Review by sidharthv96 — APPROVED** [review]

**Comment by sidharthv96** [comment]
Thank you @karistom :)

**Comment by trobbierob** [comment]
Thanks @karistom!

**Pull request merged**
