### PR TITLE
Mention obsidian has native support for mermaid

### PR DESCRIPTION
**Pull request by IanLee1521**
## :bookmark_tabs: Summary

Add "Obsidian" app as having native support for Mermaid to the Integrations documentation page.

Resolves (N/A - no issue)

## :straight_ruler: Design Decisions

Updated documentation.

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [ ] ~~:computer: have added unit/e2e tests (if appropriate)~~
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by sidharthv96** [comment]
Thanks @IanLee1521!

Just curious to know what your workflow was. Did you use the GitHub UI to edit `src/docs`?

**Review by sidharthv96 — APPROVED** [review]

**Comment by IanLee1521** [comment]
Hi @sidharthv96 - yes exactly. Since I thought this was just going to be a simple one line change, I chose to make it on the GitHub UI directly. The first failed CI lint run taught me there was a little more to it, but even then I ended up just manually editing the corresponding `docs/` file.. I'm guessing that wasn't the preferred way, however in this case I think the end result is identical (though perhaps I'm wrong).

**Comment by sidharthv96** [comment]
Just wanted to know what the flow was. 

We'll modify the CI to auto generate the docs files if the PR contains _only_ changes in _src/docs_.

**Review by mmorel-35 — APPROVED** [review]

**Comment by knsv** [comment]
Thanks!

**Comment by IanLee1521** [comment]
> We'll modify the CI to auto generate the docs files if the PR contains only changes in src/docs.

I think that would be a great improvement, thanks!

**Comment by IanLee1521** [comment]
Not sure if you'll be interested, but I just posted the video I was working on when I came across the need for this change: https://www.youtube.com/watch?v=BY1WKBcJGss (which actually includes a section of me creating this PR starting at 04:02) -- thanks again!

**Comment by dwhelan** [comment]
That's a great intro to mermaid Ian!

**Comment by IanLee1521** [comment]
Thanks @dwhelan !

**Pull request merged**
