### PR TITLE
add edgeLabelTextColor that take the color from secondaryTextColor

### LINKED ISSUE #5052: Edge labels in flow chart use primaryTextColor rather than secondaryTextColor
### Description

When I customise the theme using the documented variables to change the secondary color to the same as the primary text color, and modify the secondary text color to contrast with the secondary color, I can not see the label text as it appears to be incorrectly using the primary text color rather than the secondary text color.

### Steps to reproduce

Create a diagram using the following code:

```mermaid
%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#000',
      'primaryTextColor': '#fff',
      'secondaryColor': '#fff',
      'secondaryTextColor': '#000'
    }
  }
}%%
flowchart TD
    A[Christmas] -->|Get money| B(Go shopping)
    B --> C{Let me think}
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[fa:fa-car Car]
```

### Screenshots

image

### Code Sample

```text
https://mermaid.live/edit#pako:eNp1kU1rwkAQhv_KsCWkhQiecyjUaL1YWqj00MTDmEzcxewHuytWTP57NwlWPfSyH_M-7wwzc2alroilLIrOhQIQSvgUhidA7DlJilOIt-goTm6jX2gFbhty8R8eJGOFRHvKdKNt73uYTqcX31Ve04-_InVd3yCOSq2quxz_APdZ-kIj0_VXOLooKlTd6GPJ0XpYz0f5Jc-4Fc5LdBuYTJ7bJXmQWtGphdnjUoPj2hihdk8jP-shyM6rHiPwXKh9N0rZ4H9X1MI8X6Hx2mxulfVRt7DIxQcP6e8Vbim4XvMa0xonJVrI0G5YwiRZiaIKGxmmWrBh2gVLwzN0vS9Y6CxwB1Ohp0UlvLYs9fZACcOD158nVV7-IzMXuLMoWSjUuBClwfM2rn3YfsIMqm-tL0z3C_BRp9E
```

### Setup

- Mermaid version: v10.6.1
- Browser and Version: Google Chrome | 119.0.6045.159 (Official Build) (arm64)

### Suggested Solutions

Change the style to use secondary text color for those nodes instead

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by omer-priel**
## :bookmark_tabs: Summary

Fixed the bug in #5052 . see in Design Decisions

Resolves #5052 

## :straight_ruler: Design Decisions

For edge labels was only the field edgeLabelBackground in styles for color of the background.
I add new field called edgeLabelTextColor (edgeLabel like edgeLabelBackground and TextColor like textColor, nodeTextColor and secondaryTextColor) that take the value from secondaryTextColor
After that I used this field in the FlowChartStyleOptions and getStyles for add "color" and "fill" to edge labels

This solution fix for flowchart and for flowchart/elk and it can work for the other diagrams that has this bug with edge labels. But, I fixed only flowchart for the simplicity of this PR

I dont know if this bug need new tests?

Note: The tests is passing if you chanage the testTimeout. But thay are fiailing now beacuse of #5053  

Sory of my english :)

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added necessary unit/e2e tests.
- [x] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/development.md#3-update-documentation) is used for all new features.
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by omer-priel** [comment]
I don't know if this bug need new tests?

**Comment by sidharthv96** [comment]
Hi @omer-priel,
Can you share some example code which works in https://deploy-preview-5057--mermaid-js.netlify.app/ ?

**Comment by omer-priel** [comment]
An example of code from the issue of the bug:
[deploy-preview-5057--mermaid-js.netlify.app example](https://deploy-preview-5057--mermaid-js.netlify.app/edit#pako:eNp1kcFrgzAUxv-VR4a4QQXPHgar3XopbDDZRXt41ZcmzCQSI51U__dFZWt76CV5vO_3fY-8nFlpKmIJC4JzoQGkli6BuQQInSBFYQLhAVsKV9fdL7QSDzW14T_upcZKhbZPTW3s5HuI4_jPd5Ez-nEXhHN-hbRUGl3dZNwBblOmQQszTpc_xiAoNK_NqRRoHWSbRX7JU2Fl6xS2e4ii52FLDpTR1A-wftwaaIVpGqmPTwu_niBIz7sJI3BC6u9xkdLZ_65pgE2-w8aZZn-tZCczwGsuP4SPv1WEJe96yzkmHKMSLaRo92zFFFmFsvI_Mm-1YPO2C5b4siKOXe0K5h_nUeyc-ex1yRJnO1qxrqnQ0Ubi0aJamuMvhUyVRw)

**Review by nirname — APPROVED** [review]
Not sure why not all the lines were marked as covered by tests. Maybe they are not. PR looks good. Uniform and simple

**Review by sidharthv96 — APPROVED** [review]

**Pull request closed without merging**
