### PR TITLE
docs(README.zh-CN): fix book image src

### PR DESCRIPTION
**Pull request by aloisklink**
## :bookmark_tabs: Summary

Fixes the broken image source in the `README.zh-CN.md` file that was causing the link checker CI action to fail.

Copied from https://github.com/mermaid-js/mermaid/commit/ec026eaf8230d9f97fe4004f8ef0d294ca16a098

## :straight_ruler: Design Decisions

N/A

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [ ] :computer: have added unit/e2e tests (if appropriate)
  - Documentation only
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by sidharthv96** [comment]
Oops, Wonder why the replace all didn't fix this file.

**Comment by sidharthv96** [comment]
Thanks for the fix :)

**Comment by aloisklink** [comment]
> Oops, Wonder why the replace all didn't fix this file.

It's because the image file was called `book-banner-pre-release.jpg` in the Chinese README, but it was called `book-banner-post-release.jpg` in the English README.md file.

I had the same issue :)

**Comment by sidharthv96** [comment]
Damn, so I wasn't imagining the `pre` release I thought I saw somewhere. 😆

**Pull request merged**
