### PR TITLE
Fixes to Docs sidebar, main page and badges

### PR DESCRIPTION
**Pull request by nirname**
## :bookmark_tabs: Summary

* Left menu `collapsible` option was obsolete and did not work. Replaced, make all menu items expanded by default
* Fixed badges on the intro page, rely on classes instead of HTML structure
* Updated Vue it docs to 3.3 because of [this issue](https://github.com/vuejs/vitepress/issues/2761)

Related #2910

### Badges are the same but their behavior more consistent, content changes do not influence on layout

image
image

## :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added necessary unit/e2e tests.
- [x] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/development.md#3-update-documentation) is used for all new features.
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Review by Yokozuna59 — COMMENTED** [review]
Please rename the PR title to something more descriptive and add some images to show differences.

**Comment by nirname** [comment]
@Yokozuna59 done

**Review by huynhicode — APPROVED** [review]
Great job @nirname !

**Comment by Yokozuna59** [comment]
@nirname I've got a question: what's the expected result when you collapse a sidebar and then open another page?
The current behavior is to return all sidebars to their original state, which is uncollapsed. Wouldn't it be better to leave them in their current state?

**Comment by nirname** [comment]
@Yokozuna59 yes, it would be better, I think I'll add this to the list for the docs improvements. I thought it kept its state, but right now I see it does not

**Pull request merged**
