### PR TITLE
Contribution.md Updates

### PR DESCRIPTION
**Pull request by Aniket1026**
The PR includes some changes in the contribution.md for the beginners to help them setting the project locally.

### CODE REVIEW

**Review by sidharthv96 — CHANGES_REQUESTED** [review]
Hi @Aniket1026, thanks for the PR. 
Instead of the instructions, please add a link to https://docs.github.com/en/get-started/quickstart/fork-a-repo which is very comprehensive for a beginner. 

As a first time contributor, you have to note the following:
- The title of the PR should be descriptive and not your name.
- The PR body should follow the template we autofill. (You can't get it back now, so ignore this for now. Make sure you follow it in the future)

Thanks!

**Comment by Aniket1026** [comment]
Should I create another PR form another branch following the points you mentioned ?

**Comment by sidharthv96** [comment]
You can update this PR

**Comment by Aniket1026** [comment]
> You can update this PR

1 check is failing what should i update in order to pass that check ?

**Review by sidharthv96 — APPROVED** [review]

**Comment by sidharthv96** [comment]
Please see the logs of failing test. 
Should help you to find the problem.

**Comment by Aniket1026** [comment]
> Please see the logs of failing test. Should help you to find the problem.

I'm not able to commit after removing the eslint errors . Can you tell me what is possibly going wrong . The error is something about husky

**Comment by sidharthv96** [comment]
Please post actual logs so we can diagnose what the problem is.

**Comment by Aniket1026** [comment]
> Please post actual logs so we can diagnose what the problem is.

Should i post the screenshots ?

**Comment by sidharthv96** [comment]
Copy pasting text would be better.

**Comment by Aniket1026** [comment]
> Copy pasting text would be better.

For the ESlint errors there are 95 warnings pasting all of them wouldn't make it tougher to understand ?

**Comment by sidharthv96** [comment]
No need to paste the entire thing. Just where the error is. You can read it first. Eslint warnings won't make husky fail. Check for errors.

**Comment by Aniket1026** [comment]
> No need to paste the entire thing. Just where the error is. You can read it first. Eslint warnings won't make husky fail. Check for errors.

.husky/pre-commit: line 4: pnpm: command not found
husky - pre-commit hook exited with code 127 (error)
husky - command not found in PATH= a really big path here.

This is the error i'm getting in git

**Comment by sidharthv96** [comment]
Do you have pnpm installed?

**Comment by Aniket1026** [comment]
Yes , it is installed

**Comment by sidharthv96** [comment]
I don't have windows, so can help you only in a limited capacity. 
By looking at the GitHub actions logs, the issue is with prettier. 
I think just adding a new line after your edit might solve it. 

BTW, Although not recommended, you can use `git commit -n` to bypass pre-commit hooks (husky).

**Comment by Aniket1026** [comment]
> I don't have windows, so can help you only in a limited capacity. By looking at the GitHub actions logs, the issue is with prettier. I think just adding a new line after your edit might solve it.
> 
> BTW, Although not recommended, you can use `git commit -n` to bypass pre-commit hooks (husky).

Ohh sure , during yarn install there's a yarn.lock file created should i push it or not ?

**Comment by sidharthv96** [comment]
@Aniket1026 really appreciate the effort. 
But we cannot have blanket ESLint ignores on top of files. 

Please revert [08e75ba](https://github.com/mermaid-js/mermaid/pull/3599/commits/08e75bac57af4c72180d00b36066b085b3b5b934) and commit just the changes in contribution.md and pre-commit (if that's needed).

You can start another PR to fix ESLint warnings (which is something that would be really useful).
We can take few approaches.

1. Adding `// eslint-disable-next-line` to each errors (This can be automated, I think there was some tool for this)
2. Fixing simple issues
3. Turning off rules in eslintrc

|Issue Type|Ideal Order|
|---|---|
|Code in `.ts` & `.js` files|2,1|
|jsdoc|2,1|
|Documentation in `.md` files|2,3|

**Comment by Aniket1026** [comment]
> @Aniket1026 really appreciate the effort. But we cannot have blanket ESLint ignores on top of files (because it breaks the whole purpose of linting).
> 
> Please revert [08e75ba](https://github.com/mermaid-js/mermaid/pull/3599/commits/08e75bac57af4c72180d00b36066b085b3b5b934) and commit just the changes in contribution.md and pre-commit (if that's needed).
> 
> You can start another PR to fix ESLint warnings (which is something that would be really useful). We can take few approaches.
> 
> 1. Adding `// eslint-disable-next-line` to each errors (This can be automated, I think there was some tool for this)
> 2. Fixing simple issues
> 3. Turning off rules in eslintrc
> 
> Issue Type	Ideal Order
> Code in `.ts` & `.js` files	2,1
> jsdoc	2,1
> Documentation in `.md` files	2,3
> The current top level ignores were added during some massive PRs to keep the change list short. Ideally there should also be removed gradually and issues fixed.

Thanks for guiding so gently . So for now i should only push the contribution.md changes ? Is that so ?

**Comment by sidharthv96** [comment]
Yup, just the changes in contribution.md [and pre-commit if that's needed].

**Comment by Aniket1026** [comment]
Sorry I ended up removing the commits as they were creating conflicts and I was unaware that this will close the issue.

**Pull request closed without merging**
