### PR TITLE
Add integrations

### PR DESCRIPTION
**Pull request by remcohaszing**
## :bookmark_tabs: Summary

This adds the projects [`mermaid-isomorphic`](https://github.com/remcohaszing/mermaid-isomorphic), [`rehype-mermaidjs`](https://github.com/remcohaszing/rehype-mermaidjs), and [`gatsby-remark-mermaid`](https://github.com/remcohaszing/gatsby-remark-mermaid) to the integrations page.

This also removes [`remark-mermaid`](https://github.com/temando/remark-mermaid). This project is outdated and unmaintained.

I also maintain [`remark-mermaidjs`](https://github.com/remcohaszing/remark-mermaidjs), but I didn’t add it, because I discourage its usage in favor of `rehype-mermaidjs`.

## :straight_ruler: Design Decisions

N/A

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added unit/e2e tests (if appropriate)
- [x] :notebook: have added documentation (if appropriate)
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by remcohaszing** [comment]
The test failure seems unrelated, as I didn’t touch any code.

**Review by aloisklink — APPROVED** [review]
> I also maintain [`remark-mermaidjs`](https://github.com/remcohaszing/remark-mermaidjs), but I didn’t add it, because I discourage its usage in favor of `rehype-mermaidjs`.

Is it worth still having an entry like:

```markdown
- [remark](https://github.com/remarkjs/remark)
  - [remark-mermaidjs](https://github.com/remcohaszing/remark-mermaidjs)
    (_If you're converting markdown to HTML, you probably want to use [rehype-mermaidjs](https://github.com/remcohaszing/rehype-mermaidjs) instead_)
```

I'm mainly asking since back when I was a less experienced developer, I searched this very list for a remark mermaid plugin, and back then, even though I kinda knew what remark was, I didn't know about rehype!

But it's up to you! You probably know more about the average remark user than I do!

---

> The test failure seems unrelated, as I didn’t touch any code.

Yep, looks like somebody with commit access accidentally committed directly to `develop`. Sorry about that, we really need to set up some GitHub protections on the `develop` branch!

The test failure should be fixed by https://github.com/mermaid-js/mermaid/pull/4378 [^1]

[^1]: alternatively, you could rebase your commits onto an old working `develop` commit (e.g. bf379565285dadbba252c4736b68ec571e09ae1e), with something like: `git rebase --onto bf379565285dadbba252c4736b68ec571e09ae1e develop` if you want CI to pass

**Comment by remcohaszing** [comment]
I think you’re right about people search for remark, not rehype. I added it. It feels a bit weird to add a note though, since none of the other links have it. I think the warning in `remark-mermaidjs` itself is sufficient.

**Comment by knsv** [comment]
Thanks @remcohaszing, we appreciate your input on this!

**Pull request merged**
