### PR TITLE
Add Zenuml support

### LINKED ISSUE #3435: Add ZenUML Support
Hey, author of ZenUML here.

**Is your feature request related to a problem? Please describe.**
ZenUML (ZenUML.com) is a diagram-as-code solution that convert text to sequence diagrams. ZenUML has a Confluence add-on, in which we integrated with Mermaid to extend the capability to more diagrams (many thanks). Many of our clients have asked us to unify the editing experience.

Screen Shot 2022-09-10 at 9 45 52 am

Screen Shot 2022-09-10 at 9 48 11 am

More introduction of ZenUML can be found here: https://modeling-languages.com/zenuml-drawing-sequence-diagram-easier-faster/

**Describe the solution you'd like**
I would like to integrate ZenUML into mermaid so that users can use ZenUML flavour DSL inside mermaid. ZenUML renderer is an open-source library (under MIT license). I am happy to implement the integration and pull-request.

**Describe alternatives you've considered**

- Confluence users use the ZenUML add-on - https://marketplace.atlassian.com/apps/1218380/zenuml-sequence-diagram?tab=overview&hosting=cloud
- JetBrains users use the ZenUML plugin - https://plugins.jetbrains.com/plugin/12437-zenuml-support
- Desktop users use our desktop applications - https://zenuml.com
- Some enterprise users integrate with our renderer library directly - https://www.npmjs.com/package/vue-sequence
- Most other users use the online editor - https://app.zenuml.com/ or https://zenuml.cn

Should you need more information, please let me know. Send me an email at peng(AT)zenuml.com or DM @PenngXiao on Twitter. Thanks.

### PR DESCRIPTION
**Pull request by MrCoder**
## :bookmark_tabs: Summary

Adding support for ZenUML Sequence Diagram.

Resolves #3435 

## :straight_ruler: Design Decisions

ZenUML support code (with the source code of ZenUML/core) is in the mermaid-zenuml folder. Documents and Test are added to corresponding folders.

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added unit/e2e tests (if appropriate)
- [x] :notebook: have added documentation (if appropriate)
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by sidharthv96** [comment]
Converting to draft to prevent accidental merging. 
After discussion, we've decided to split the zenUML code into a separate repo so that it's easier to maintain. 
We underestimated the size of zenUML, definitely didn't expect 3.5k files.

Adding this into mermaid repo will make it gigantic and will also be hard to maintain. 
Separate repo solves the issue. 

@MrCoder I'll help with the move as you've poured a lot of time and effort into this. I hope you understand why we have to go with this approach. 

To avoid any further complications, let's discuss what we're planning to do here.

## Integrating ZenUML to Mermaid
Objective: Move ZenUML core code to a location where mermaid maintainers have access to maintain and make releases to the `@mermaid/mermaid-zenuml` package. @MrCoder will still be the code owner and core maintainer. 

Current plan: Create a `mermaid-js/zenuml-core` repo and host the code there.

Way forward:

```mermaid
graph TD
    A[Create mermaid/zenuml-core] --> C{Will Zenuml/core be archived?}
    C -->|Yes| D[Keep replica of zenuml-core in mermaid/zenuml-core]
    C -->|No| E[What's the plan to keep both repos in sync?]
    D --> Release[Release zenuml core package from this repo]
    Release --> Ref[Create mermaid-zenuml diagram in mermaid repo]
    E --> NoRef[mermaid-zenuml cannot add zenuml-core as dependency <br> as it will not be released from our repo]
    NoRef --> Standalone[mermaid-zenuml package will be built and published from mermaid/zenuml-core repo]
```

**Comment by aloisklink** [comment]
> After discussion, we've decided to split the zenUML code into a separate repo so that it's easier to maintain.

I agree!

The current Mermaid source-code is only 575 files (counted with `git ls-files | wc -l`), so adding 3000+ files makes the repo many times larger.

I'm struggling to even review the code changes, because the moment I click review on GitHub, GitHub freezes up and my tabs/browser crashes! The mermaid team is struggling a bit to maintain the current mermaid source code, and adding more code to maintain will be even harder!

**Comment by MrCoder** [comment]
@sidharthv96, @aloisklink, thank you for your help. Just to clarify, most of the 3000+ are svg icons (AWS Cloud Service, GCP, Azure, etc). Only a small proportion of these icons are used, but we don't want to maintain a handpicked list of files, as they are published as a whole by each provider.

Not counting the svg icons, the total number of files (including test) is 249 with `git ls-files -- . ':!:*/assets/*' | wc -l`.

**Comment by sidharthv96** [comment]
@MrCoder, I understand that the files are not directly from ZenUML, but, the files are there.
Also, ZenUML and mermaid are entirely unique codebases, so it'll be much easier for us to use the different repo approach. 

Can we discuss which path we should take from the flowchart in my previous comment?

**Comment by MrCoder** [comment]
> Can we discuss which path we should take from the flowchart in my previous comment?

The left path ("YES") sounds good to me. Let me know if you need help.

**Pull request closed without merging**
