### PR TITLE
New Diagram: Architecture

### LINKED ISSUE #5367: Proposal: Cloud Architecture Diagram
### Proposal

# Proposal: Cloud Architecture Diagram

## Motivation
The recent addition of Block diagrams greatly helped in allowing users precise control over where nodes (blocks) are placed. While they are useful for representing API or Network diagrams, it proves to be unweidly for cloud architecture diagrams such as [(1)](https://www.lucidchart.com/pages/architecture-diagram) or [(2)](https://www.ilograph.com/blog/posts/fixing-aws-architecure-diagrams-distributed-load-testing/)

## Terminology
* Service: a node within a diagram. Represents services such as from AWS, Azure, Docker, etc
* Group: a collection of related services (similar in presentation to subgraphs for other diagrams). This could be a VPC on AWS, different APIs which talk to one another, etc

## Syntax

* A group can be defined as `group {id}[{title}] (in {group_id})?` where `id` is the value to reference the group and `title` is the text to display along othe border. `(in {group_id})?` can optionally be used to position a group within another group
* A service can be defined as `service {id}({icon})[{title}] (in {group_id})?` where `id` is the value to reference the service, `icon` is the `svg` resource to use for the node (more on this later), and `title` is the text to display under the service. Like with groups, `(in {group_id})?` can be used to declare which grouping this service falls under. If no group is defined, it will default to be free floating and the renderer will decide where it goes
* Services and groups can be related with the syntax `{id_1} (<)?(L|R|T|B)-([{title}])?-(L|R|T|B)(>)? {id_2}` where `id_1/2` are the two services/groups to connect and `title` is the optional text to display along the line. The positional relation between services / groups is declared using `L|R|T|B` on both sides of the arrow. For example, `L` on the LHS means the line will come out of the left of the service `id_1`

### Example

The diagram shown in [(2)](https://www.ilograph.com/blog/posts/fixing-aws-architecure-diagrams-distributed-load-testing/) can be represented as:
```
architecture

    group rest_api[Rest API]

    group web_console[Web Console]

    group image_pipeline[Image Pipeline]
    group codepipeline(codepipeline)[AWS CodePipeline] in image_pipeline
    
    group testing_engine[Load Testing Engine]
    group vpc(vpc)[Amazon VPC] in testing_engine


    service cf(cloudfront)[AWS Cloudfront] in web_console
    service store(s3)[Amazon S3] in web_console

    cf <L--R> store


    service api_gateway(apigateway)[Amazon API Gateway] in rest_api
    service lambda(lambda)[AWS Lambda] in rest_api
    service congnito(amzn_cognito)[Amazon Cognito] in rest_api
    service iam(amzn_iam)[AWS IAM] in rest_api

    api_gateway <L--R> lambda
    api_gateway <B--T> congnito
    congnito <L--R> iam

    web_console <B--T> rest_api

    service store_2(s3)[Amazon S3] in testing_engine
    service db(dynamodb)[Amazon DynamoDB] in testing_engine
    service sqs(amzn_sqs)[Amazon SQS] in testing_engine
    service lambda_2(lambda)[AWS Lambda] in testing_engine
    service ecr(ecr)[Amazon ECR] in testing_engine
    service cw(cloudwatch)[Amazon CloudWatch] in testing_engine

    store_2 <R--T> lambda_2
    db <R--L> lambda_2
    sqs <R--B> lambda_2

    service fg(fargate)[AWS Fargate] in vpc

    lambda_2 <R--L> vpc
    vpc <R--L> ecr
    vpc R--L> cw

    service docker(docker)[Taurus Docker Image] in image_pipeline
    service store_3(s3)[Amazon S3] in codepipeline
    service codebuild(codebuild)[AWS CodeBuild] in codepipeline

    docker R--L> codepipeline 
    store_3 R--L> codepipeline
    image_pipeline R--T> ecr
```

### Considerations
* Should `N/S/E/W` be supported alongside or instead of `L/R/T/B`?
* `group` and `service` are names I quickly came up with. I'm sure there are better options.
* Alternate ideas for positioning services? I haven't thought of this from the renderer's perspective so I currently don't know if there are flaws with this approach.

## SVG Icons

As mentioned earlier, the `icon` field for a service declaration will map to a SVG icon. Currently to use external SVG icons in Mermaid, HTML tags need to be used which points to the icon. This method isn't practical for a digram in which every node references an icon. Since we likely wouldn't want to host the icons within Mermaid for common services (either due to legal requirements or increasing the bundle size), I belive a standardized system should be implemented where icons can be defined and registered in the `initialize()` step. A standard API can additionally be exposed so users can create their own 3rd party modules which contains bundles of icons.

Since there are many ways to go about implementing this functionality, I'd love to hear others thoughts. If approval is given for begining work on this diagram type, svg handling should be moved to its own issue and potentially implemented for another diagram for testing before moving forward with the architecture diagram.

Relevent issues: #3358, #3746, #3124, #1723

### Use Cases

_No response_

### Screenshots

_No response_

### Syntax

_No response_

### Implementation

I will try and implement it myself.

### PR DESCRIPTION
**Pull request by NicolasNewman**
# :bookmark_tabs: Summary

Architecture diagrams allows users to show relations between services

Resolves #5367

# :straight_ruler: Design Decisions

### Terminology
* Service: a node within a diagram. Represents services such as from AWS, Azure, Docker, etc
* Group: a collection of related services (similar in presentation to subgraphs for other diagrams). This could be a VPC on AWS, different APIs which talk to one another, etc

### Syntax

Currently, the syntax is defined as:

* Services are defined as `service {id}({icon})[{title}] (in {group_name})?`
* Groups are defined as `group {id}[{title}] (in {group_id})?`
* Edges are defined as `{id_1} ( ( )?(L|R|T|B)--(L|R|T|B)( ) )? {id_2}`

Once I transition from jison to Langium, I plan to add the following extensions:

* Groups: `group {id}({icon})[{title}] (in {group_id})?`
  * Allow icons to be used for group names
* Edges: `{id_1} ( ( )?(L|R|T|B)-([{label}])-(L|R|T|B)( ) )? {id_2}`
  * Allow edges to have a label
  * Allow forked edges traversing the XY axis (see Layout for more info). I've yet to decide on the syntax for this
* Services: `service {id}( ({icon}) | ("{text}") )[{title}] (in {group_name})?`
  * Allow text to be used for a service instead of an icon

Additionally, the syntax for groups (and potentially forked edges?) will be modified to better follow a declare then organize approach

## Layout
* The positions of services are determined by specifying a required direction for an edge between the two
* Edges which traverse the X & Y axis (LT, RB, etc) are connected by two perpendicular lines
* Each service can only have one edge per side
* Internally, a spatial map of each service is maintained which specifies an (x,y) coordinate of where each service is in relation to one another ([0,1] is above [0,0]). This forces the layout to have a consistent grid like pattern

### Comments
As mentioned in the issue, the LRTB syntax goes against the ethos of Mermaid. Additionally, while the spatial map creates very neatly organized layouts, it prevents users from having multiple edges going out of one side. Part of the reason I began designing it this way was to avoid this diagram type from essentially being a flowchart with icons. 

Going forward, there's a few options that can fix this problem:

1. Make the LRTB syntax optional. If they aren't ever specified, don't use the spatial map for generating the constraints for `fcose` and let it figure things out on its own.
2. Keep the LRTB syntax required and instead add svg icon support to flowcharts. Ultimately the two diagram types are very similar in how they represent nodes and edges. My main reasoning for adding this new diagram type other then SVG support was for more precise control over node positioning like with block diagrams. I've already been using flowcharts to quickly mock up architecture diagrams before making something nicer in softwares like Lucidcharts.

No matter which option we choose, the LRTB syntax should be extended to:

1. Allow forked edges. This means one edge out the X/Y axis would split into more edges that would expand outwards in the opposite axis. This would solve the issue of being limited to only a max of 4 edges per service.

## SVG Icons

SVG icons are currently created and accessed through helper functions inside of [rendering-util/svgRegister.ts](https://github.com/NicolasNewman/mermaid/blob/5367/architecture-diagram/packages/mermaid/src/rendering-util/svgRegister.ts). A global object stores the mapping of icon names to `IconResolvers` defined as 

```ts
type IconResolver = (
  parent: Selection<SVGGElement, unknown, Element | null, unknown>,
  width?: number
) => Selection<SVGGElement, unknown, Element | null, unknown>;
```

IconResolvers can easily be created through the helper function `createIcon`. This function takes the SVG code as a string along with the original resolution. It returns a CB function taking the element to inject the SVG into and optionally a different size to scale it by.

```ts
const createIcon = (icon: string, originalSize: number): IconResolver => {
  return (
    parent: Selection<SVGGElement, unknown, Element | null, unknown>,
    size: number = originalSize
  ) => {
    parent.html(`<g style="transform: scale(${size / originalSize})">${icon}</g>`);
    return parent;
  };
};
```

A few generic icons I've created are located in [rendering-utils/svg/](https://github.com/NicolasNewman/mermaid/tree/5367/architecture-diagram/packages/mermaid/src/rendering-util/svg). Additional icons can be added through the new `iconLibraries` [config option](https://github.com/NicolasNewman/mermaid/blob/6bd1da219ad474d4c81eebfc0d50f5731f089843/packages/mermaid/src/mermaidAPI.ts#L535). The types in `svgRegister.ts` are now exported from `mermaid.ts`, allowing developers to create their own icon library packages.

```ts
// Example icon

// rendering-util/svg/database.ts
export default createIcon(
  `<g>
      <rect width="80" height="80" style="fill: #087ebf; stroke-width: 0px;"/>
     ...
</g>`,
  80
);

// rendering-util/svg/index.ts
const defaultIconLibrary: IconLibrary = {
  database: database,
  // ...
};

// index.html
mermaid.initialize({
  theme: 'base',
  startOnLoad: true,
  // This is just an example. It is already loaded by default within MermaidAPI.ts
  iconLibraries: [defaultIconLibrary],
  // ...
});
```
### Alternatives
From conversations in the linked issue, ZenUML already handles SVG icons on their end. Upon furthur inspection, they rely on [declaring an svg module](https://github.com/ZenUml/core/blob/4a1d02837337bef0ebdedeb766192bb53d4d17a8/types/svg.d.ts) which essentially resolves the imported SVG as a string. Since the end result of both of these approaches are the same (having the SVG code as a string), personally I think it's debatable if we want to go through with this extra step. The main con I foresee is that it'll add more work for people who want to make their own icon library package as they will need to setup the declarations themselves.

On a side note, it looks like ZenUML directly added the official [AWS icons](https://aws.amazon.com/architecture/icons/) to their repo [here](https://github.com/ZenUml/core/blob/4a1d02837337bef0ebdedeb766192bb53d4d17a8/src/components/DiagramFrame/Tutorial/Icons.ts). [IANAL](https://en.wikipedia.org/wiki/IANAL) but the terms Amazon states are:

> Customers and partners are permitted by AWS to use the resources below to create architecture diagrams

This may mean we can make official icon packs in seperate packages, or have them be lazy loaded as needed. Ultimately I'll leave that decision up to you as that isn't my area of specialties.

# Todo

* [x] Unit tests
* [X] Documentation
* [x] More generic default icons? If anyone has ideas let me know and I can put something together in Illustrator
* [X] Convert parser from jison to Langium
* [X] Implemented parser extensions
    - [X] Edge labels
    - [X] Icons as group names
    - [X] Text instead of service icon 
* [x] Forked edges
* [x] Edges between groups
* [x] More control over styling 

# :clipboard: Tasks

Make sure you

- [X] :book: have read the [contribution guidelines](https://mermaid.js.org/community/contributing.html)
- [x] :computer: have added necessary unit/e2e tests.
- [x] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://mermaid.js.org/community/contributing.html#update-documentation) is used for all new features.
- [X] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by NicolasNewman** [comment]
@sidharthv96 Continuing our conversation from the issue, I commented on SVG loading and my thought process behind how the layout is handled. Let me know what your thoughts are.

Additionally, an example of what forked edges would look like once implemented:
image

Regarding multiple edges going into one side of a service, it's possible but I'll need to spend some time figuring out the cleanest way to implement that functionality. Ultimately I was planning on using forked edges to handle that scenario but after looking at your example the arrows can't be as neatly represented the same way through forked edges.
image

**Comment by NicolasNewman** [comment]
Here is where the renderer currently stands:

From a stylistic standpoint I'm considering shortening the edges so they don't overlap with the service label.

## Simple diagram with an icon in the group name
image

## Groups within groups
image

## 90 degree edges
image

## Edge Arrows
image

## Edge Labels
image

image

**Comment by hemeroc** [comment]
Regarding the icons it would be awesome if it's possible to use any of those:
- https://ionic.io (MIT License)
- https://feathericons.com/ (MIT License)

**Comment by sidharthv96** [comment]
Solid progress @NicolasNewman 👍 

Minor note regarding readability of labels. 

I feel the label that goes from top to bottom and right to left is more readable.

image

---

image

image

**Comment by NicolasNewman** [comment]
Update on diagram syntax changes:

## Edges between groups
One limitation of fcose is the 3 constraint parameters don't factor in groups. Since this prevented me from directly having edges between group nodes, I had to implement a work-around by extended the parser to signal that an edge endpoint should connect to the group border and not the node itself. In practice, the implementation looks like:
image
```
architecture
        group left_group(cloud)[Left]
        group right_group(cloud)[Right]
        group top_group(cloud)[Top]
        group bottom_group(cloud)[Bottom]
        group center_group(cloud)[Center]

        service left_disk(disk)[Disk] in left_group
        service right_disk(disk)[Disk] in right_group
        service top_disk(disk)[Disk] in top_group
        service bottom_disk(disk)[Disk] in bottom_group
        service center_disk(disk)[Disk] in center_group

        left_disk{group} (R--L) center_disk{group}
        right_disk{group} (L--R) center_disk{group}
        top_disk{group} (B--T) center_disk{group}
        bottom_disk{group} (T--B) center_disk{group}
```
Note that the `{group}` modifier doesn't have to be applied to both ends.

## Forked edges
I decided to handle this problem with the concept of a junction node. Internally, its positioned and rendered almost identically to service nodes with the exception that its entirely transparent with no label associated.

image
```
architecture
        service left_disk(disk)[Disk]
        service top_disk(disk)[Disk]
        service bottom_disk(disk)[Disk]
        service top_gateway(internet)[Gateway]
        service bottom_gateway(internet)[Gateway]
        junction juncC
        junction juncR

        left_disk R--L juncC
        top_disk B--T juncC
        bottom_disk T--B juncC
        juncC R--L juncR
        top_gateway B--T juncR
        bottom_gateway T--B juncR
```

## Additional example
image
```
architecture
        group left
        group right
        service left_disk(disk)[Disk] in left
        service top_disk(disk)[Disk] in left
        service bottom_disk(disk)[Disk] in left
        service top_gateway(internet)[Gateway] in right
        service bottom_gateway(internet)[Gateway] in right
        junction juncC in left
        junction juncR in right

        left_disk R--L juncC
        top_disk B--T juncC
        bottom_disk T--B juncC


        top_gateway (B--T juncR
        bottom_gateway (T--B juncR

        juncC{group} R--L) juncR{group}
```

## Remaining Goals
As of now, the primary features that remain are:
1) Controlling arrow orientation for junction edges
2) Flexible styling
3) Unit tests
4) Finalize the docs

## Lingering Questions
@sidharthv96 
1) Should a mode be added which handles the positioning on its own? I've mentioned my opinion on that earlier where I feel that it would then be very similar to flowcharts. I personally think it would make more sense to update flowcharts to have the same svg icon support.
2) How to handle the inclusion of AWS/Azure/etc icons. Should it be included with Mermaid and dynamically loaded? Should it be split off into its own package? If so, who will host it? (that could also serve as a template for anyone who would like to make their own icon library)

**Comment by hemeroc** [comment]
Just to share some opinions

> 1. Should a mode be added which handles the positioning on its own?

Imho, yes. Architecture diagrams tend to get very large and sometimes some manual positioning would be extremely helpful

> 2. How to handle the inclusion of AWS/Azure/etc icons. Should it be included with Mermaid and dynamically loaded?

I would include them and offer the possibility to reference external images. The reason for this is that otherwise we will run into CORS issues e.g. in the GitHub integration as external SVGs cannot be loaded to prevent XSS.

**Comment by NicolasNewman** [comment]
@sidharthv96 When you have the chance, could we get the review process started for this PR? I'm happy with the results as it stands and getting some feedback would be great!

I've recently added documentation for using icons and once I know the implementation details won't change I'll update the docs with the available icons (ideally in an automated fashion akin to how the contributors are added).

**Comment by sidharthv96** [comment]
I'll just note down points I find here, will do a full review soon. 

architecture-beta should be used as the diagram keyword, this gives us a bit of wiggle room to tweak syntax till we finalize.

Issues with icon sizing
image

**Comment by andig** [comment]
> As mentioned in the issue, the LRTB syntax goes against the ethos of Mermaid.

Looking at the examples it's not clear to me how to give the edges arrow ends? Can we do this similar to flow charts?

**Comment by NicolasNewman** [comment]
> > As mentioned in the issue, the LRTB syntax goes against the ethos of Mermaid.
> 
> Looking at the examples it's not clear to me how to give the edges arrow ends? Can we do this similar to flow charts?

You can add `( / )` to the ends of the arrows to add them.

For example:
```
architecture
        service servC(server)[Server 1]
        service servL(server)[Server 2]
        service servR(server)[Server 3]
        service servT(server)[Server 4]
        service servB(server)[Server 5]

        servC (L--R) servL
        servC (R--L) servR
        servC (T--B) servT
        servC (B--T) servB

        servL (T--L) servT
        servL (B--L) servB
        servR (T--R) servT
        servR (B--R) servB
```

image

**Comment by NicolasNewman** [comment]
> I'll just note down points I find here, will do a full review soon.
> 
> architecture-beta should be used as the diagram keyword, this gives us a bit of wiggle room to tweak syntax till we finalize.
> 
> The bundle size has a 40% increase, which, I assume is mostly the icons? So we'd definitely want to move icons to a separate package. We can release it under the mermaid org itself. image
> 
> Issues with icon sizing image

How did you test the diagram to get that result? I can't seem to reproduce it

**Comment by andig** [comment]
> You can add ( / ) to the ends of the arrows to add them.

Not being a mermaid or architecture native, consistency would be a plus for me. Worth noting that the `flowchart` uses a different notation for array ends.

**Comment by knsv** [comment]
Hi @NicolasNewman!

This looks really promising! 

There are some ongoing projects that might be good for you to be aware of, as they touch on what you are doing here:

The first one is: Refactoring Rendering in Mermaid (#5237):
	•	We are separating layout from rendering.
	•	It simplifies adding new layout algorithms, as most rendering details remain unaffected—only the sizing of nodes is layout-specific.
	•	It will also ease the introduction of new diagrams. You simply set up data in the Data4Layout structure, add necessary node types, and hand it over to rendering. Reusing shapes from existing diagrams becomes trivial. New layout algorithms can be added as needed; we support ELK and Dagre from the start.
	•	It also adds native support for Rough.js/hand-drawn look.

The initial PR will convert flowcharts and state diagrams, with plans to extend this to all graph-based diagrams.

Note: This shouldn’t block your initial PR, but it would be great to collaborate on converting to the new structure eventually, allowing for multiple layout options.


The second activity is that we are adding a new Syntax for Flowchart attributes (Another PR):
	•	This will simplify adding attributes to nodes, enabling new flowchart shapes without creating new shorthand for each.
	•	It introduces a `shape` attribute for more exotic shapes, avoiding the limited combinations of ({[]})/.
	•	We are also considering an icon attribute, which aligns well with your icon functionality. I agree on the value of lazy-loaded icon packs to manage the potentially large number of icons. One should probably able to add external icon packs as well.

Looking forward to the architecture diagrams as well as the icons.

**Comment by knsv** [comment]
Another note on the syntax:
```
architecture
        group left
        group right
        service left_disk(disk)[Disk] in left
        service top_disk(disk)[Disk] in left
        service bottom_disk(disk)[Disk] in left
        service top_gateway(internet)[Gateway] in right
        service bottom_gateway(internet)[Gateway] in right
        junction juncC in left
        junction juncR in right

        left_disk R--L juncC
        top_disk B--T juncC
        bottom_disk T--B juncC


        top_gateway (B--T juncR
        bottom_gateway (T--B juncR

        juncC{group} R--L) juncR{group}
```

In the defence of consistency. What if the port could be attached to the node for instance with a colon then you could use regular mermaid arrow syntax to simplify for users. Then this:
```
 juncC{group} R--L) juncR{group}
```

would turn into:
```
juncC{group}:R --> juncR{group}:L
```
or even like this depending on the grammar
```
juncC{group}:R --> L:juncR{group}
```
(I suspect the grammar with the port at the end is easier to handle)

**Comment by NicolasNewman** [comment]
@knsv 

I'm not particularly attached to the current syntax. I actually like the colon version more in the 2nd example you gave.

I'll take a look at the first PR you linked, it sounds like an exciting change! I'd be happy to collaborate on that in the future.

With regards to icons, I added a page to the documentation in this PR regarding how to use icons and create external icon packs. Let me know your thoughts once you get the chance to look at it. It's designed to where it should easily be easy to integrate with other diagrams but there may be some factors I haven't considered.

**Comment by wgordon17** [comment]
Just out of curiosity...how _close_ is this feature to becoming reality?

**Comment by knsv** [comment]
We are getting close to getting this in. Rough guess 1-2 weeks.

**Comment by ashishjain0512** [comment]
@NicolasNewman Awesome work. @knsv and I went through the demos and thought this diagram type be a great addition.

We think that using the Icon packs that are lazily loaded makes sense for the Icon registering and loading, but the ZenUML approach to creating the Icon pack will be easier to maintain. The `getIcon()` internal API in svgDraw can stay the same.

We should make several Icon packs like AWS, Google, mermaid, etc, in the repo, and lazy load them in Mermaid initialize.
This will help other members of the mermaid open-source community to create different icon packs, and users can add and use the ones they want.

**Comment by knsv** [comment]
Once the conflicts are resolved, we will merge this PR.

**Comment by NicolasNewman** [comment]
Conflicts are now resolved.

@ashishjain0512 Do you want me to convert the other icon packs currently in this PR to be lazy loaded as well? Currently only aws:full is. 

I'm assuming the structural changes will be made afterwards? One improvement to the documentation of this feature I haven't touched on yet was adding the names and a preview of the icons available. I'm not as familiar with the auto-generation portion of the documentation but I'd think another benefit of using the ZenUML approach is SVG previews on the docs can more easily be added in an automated fashion then if it were in a TS file.

**Pull request merged**
