### PR TITLE
fix(pie): align slices and legend orders

### LINKED ISSUE #4772: Pie slices and legend are in opposite order
### Description

In clockwise, the slices are ordered in desc order, but the legend is ordered in asc. 

image

### Steps to reproduce

Render sample pie

### Screenshots

_No response_

### Code Sample

_No response_

### Setup

_No response_

### Suggested Solutions

Possible regression from https://github.com/mermaid-js/mermaid/commit/9563b221327e4ac50f87d9e14626c974e4852a13

If we reverse the order of legend, it should be fine. 

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Yokozuna59**
## :bookmark_tabs: Summary

Just simple sorting.

Before:

image

After:

image

Resolves #4772

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [ ] :computer: have added necessary unit/e2e tests.
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by Yokozuna59** [comment]
Although I'm not sure why the color order changed.

**Comment by sidharthv96** [comment]
As long as the colors match, the order changing is not an issue.

But, does the order match the themevariables of pie1, pie2, etc?

**Comment by Yokozuna59** [comment]
> But, does the order match the themevariables of pie1, pie2, etc?

I'm not sure, I don't know how to test it.

**Comment by sidharthv96** [comment]
> I'm not sure, I don't know how to test it.

There you go. It works. 

https://deploy-preview-4774--mermaid-js.netlify.app/edit#pako:eNpVj81qwzAQhF9l2V7jYIe4UF3bSymBQKD0oMtWWrkC_QRZOoSQd6_kxIXOcb5hmLmiippRYNd1MqgYjJ2EDFCVf9jzJyVL347nh9l0tjwIkPhk-t4YI_Ef2t3Rfmz-0lpNeFTa7Bg--ALsannIM9gAxxR1URm-7iGJr-SULV4iCNjvti_PKzjGTPO8orHf9uOKDjQF_kNDRcOK3lMMiwsjbtBz8mR1vXxtAYnLT4lttmZDxeW2_FajVHI8XYJCkVPhDZazpsxvlqZEHoUhN_PtF0qMYF8

**Review by sidharthv96 — APPROVED** [review]

**Comment by sidharthv96** [comment]
Merging without tests as it's covered in E2E.

**Pull request merged**
