### PR TITLE
Bug/1061 Cannot mark members as protected in class diagram

### LINKED ISSUE #1061: Cannot mark members as protected in classDiagram
Attempting to mark a member as protected in a class diagram by using the octothorpe (hash) character causes the graph to not render. I'm attempting this based on the [classDiagram documentation](https://mermaidjs.github.io/#/classDiagram?id=visibility).

Specifically, the following code:

    classDiagram
    class MyClass
    MyClass : #mytest

Causes the following error:

    Parse error on line 3:
    ...s MyClassMyClass : #mytest
    ----------------------^
    Expecting 'NEWLINE', 'EOF', got 'PUNCTUATION'

The private, public and package qualifiers all seem to work appropriately.

This reproduces using the [Mermaid Live Editor](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiY2xhc3NEaWFncmFtXG5jbGFzcyBNeUNsYXNzXG5NeUNsYXNzIDogI215dGVzdFxuXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ/error/UGFyc2UgZXJyb3Igb24gbGluZSAzOgouLi5zIE15Q2xhc3NNeUNsYXNzIDogI215dGVzdAotLS0tLS0tLS0tLS0tLS0tLS0tLS0tXgpFeHBlY3RpbmcgJ05FV0xJTkUnLCAnRU9GJywgZ290ICdQVU5DVFVBVElPTic)

I'm using Windows 10 with Chrome 78.0.3904.87

I can work around this cosmetically by using [`#35;`](https://github.com/mermaid-js/mermaid/issues/947) but it took me a while to figure that out. It's unclear to me whether I lose any functionality by doing so. (I believe not.)

### PR DESCRIPTION
**Pull request by jgreywolf**
Using # to indicate protected status of a member or method causing parser error when not used inside class declaration brackets {}.  Removed '#' from `LABEL` regex

Resolves #1061

### CODE REVIEW

**Comment by chris579** [comment]
Great, thanks for your contribution. According to our [contribution docs](https://github.com/mermaid-js/mermaid/blob/master/CONTRIBUTING.md#branching), prs go into `development`. Could you rebase onto it and then change the target branch to it? Thanks!

**Comment by jgreywolf** [comment]
> Your newly added unit test doesn't pass, you might want to look into that.

How can I run unit tests locally? Not finding anything in documentation...

**Comment by jgreywolf** [comment]
Or I can just fix the simple mistake in the test

**Comment by jgreywolf** [comment]
I fixed the syntax error in the failing test (duh), and now those are all fine.  But I see that the GitHub builds failed..  I dont understand why, based on the messages provided though.

**Comment by chris579** [comment]
> I fixed the syntax error in the failing test (duh), and now those are all fine. But I see that the GitHub builds failed.. I dont understand why, based on the messages provided though.

This is not related to your code. We just introduced GitHub builds as a testing phase, for now travis matters.

**Comment by jgreywolf** [comment]
@knsv Are you saying that you would rather there be a separate test?  As opposed to just adding to an existing test which is what I had done :)

Which does make sense

**Comment by knsv** [comment]
Good work with this one!

**Pull request merged**
