### PR TITLE
Showcase section to the docs - keepings docs up to date

### PR DESCRIPTION
**Pull request by Omerr**
After discussing with @sidharthv96 and following #3936, I created a `Showcase` section to the docs.

### CODE REVIEW

**Review by sidharthv96 — CHANGES_REQUESTED** [review]
Hi @Omerr ,
Swimm looks neat! 
Can you move the showcase section inside Misc and rename Misc to Ecosystem?

image

You can add a showcases.md page which links to the swimm showcase page.
This way, we can accommodate more showcases without cluttering the main sidebar with individual showcases and tag-lines…

**Comment by Omerr** [comment]
> Hi @Omerr , Swimm looks neat! Can you move the showcase section inside Misc and rename Misc to Ecosystem?
> 
> image
> 
> You can add a showcases.md page which links to the swimm showcase page. This way, we can accommodate more showcases without cluttering the main sidebar with individual showcases and tag-lines…

Thank you @sidharthv96!
I updated accordingly, please let me know if these changes meet your expectations.

**Comment by sidharthv96** [comment]
LGTM, I'll merge once I modify the redirect logic to handle these route changes as well.

**Comment by Omerr** [comment]
Thank you @sidharthv96 🙏🏻

**Pull request merged**
