### PR TITLE
Fixed styling for lines for ELK flowchart

### LINKED ISSUE #4813: Elk Rendering for Flowcharts does not support Title and arrow styling
### Description

Elk Rendering for Flowcharts does not support title and arrow styling.

### Steps to reproduce

Use the sample code below. 

### Screenshots

**without Elk rendering :** 
image

**with Elk rendering activated :** The Title disappears and the "Master Data" Arrow is plain instead of dotted.
image

### Code Sample

```text
---
title: Interfaces for B
---
%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart LR
A-->|"Guarantee"|B
C-->|"User attributes"|B
C-.->|"Master data"|B
C-->|"Exchange Rate"|B
C-->|"Profit Centers"|B
C-->|"Vendor Partners"|B
C-->|"Work Situation"|B
C-->|"Customer"|B
C-->|"Profit Centers"|B
B-->|"Guarantee"|C
```

### Setup

- Mermaid version: Live Editor 10.3.0
- Browser and Version: Chrome

### Suggested Solutions

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by itsalam**
## :bookmark_tabs: Summary

- Added nodeSpacing for line length (note that config seems to be overwritten to default values due to a race condition that elk triggers) 
- Inserts specified title as intended
- Applies styling from the db object
- Fixed a bug where db object returned null due to importing syntax convention. 

Screenshot 2023-09-15 133039

Resolves #4813 

## :straight_ruler: Design Decisions

Removed excessive padding, as on render the padding is for an empty graph and the intended graph is inserted below it.
As edgeNodeBetweenLayers already existed as a parameter, it seems like it is the most suitable parameter for adjusting line length. Also re-added working test suites to the elk flowchart to slowly introduce a working test suite. 

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added necessary unit/e2e tests.
- [x] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/development.md#3-update-documentation) is used for all new features.
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Review by sidharthv96 — APPROVED** [review]
Can you also check if we can add the line length property working in elk too? (Can go in a different PR if the changes are big, no need to block this one.)

```mermaid
flowchart
A --> B
A ---> C
A ----> D
```

```mermaid
flowchart-elk
A --> B
A ---> C
A ----> D
```

**Comment by sidharthv96** [comment]
image
image
image


When comparing the images from the issue and your final image, I see a few minor issues.

1. Title is not centered. (needs to be fixed)
2. The arrows overlap (Will be fixed if you sync with develop) image

**Review by sidharthv96 — CHANGES_REQUESTED** [review]
Please center the title.

**Comment by itsalam** [comment]
@sidharthv96, are we good to go?

**Comment by huynhicode** [comment]
Hi @itsalam, @sidharthv96 is currently on vacation.

It looks like there is a linting issue in your PR.  Can you see if running `pnpm -w run lint:fix` fixes the issue?

**Comment by itsalam** [comment]
Hi there @huynhicode, 

Yeah, I had earlier trouble with the pre hook commit linting and @sidharthv96 suggested skipping them. Found a workaround that should pass for now. Feel free to write back if theres anything else.

**Comment by sidharthv96** [comment]
The E2E tests are failing for ELK. @itsalam can you please fix that?

**Comment by martin-schaefer** [comment]
Is anybody still working on that? Would be so glad if the elk renderer supports the styling of links.

**Pull request merged**
