### PR TITLE
Fixes support of the macro `ContainerQueue_Ext` for C4 diagrams definition.

### LINKED ISSUE #4576: As a mermaid user, I want to render C4 diagram with the ContainerQueue_Ext macro
### Description

The C4 container, or context diagram cannot be rendered if its definition contains the macro `ContainerQueue_Ext`. Note that the macro `ContainerQueue` is rendered as expected.

Both, the [online editor](https://mermaid.live/edit#pako:eNpVkE1rhDAQhv_KMqcuWDVGjXrd7rGH0lsJlFkTNaCJjUnZD_zvjRYKPc2bZybvfDygNUJCA6f8ZLRDpaXl-k--eenl5_nqnjpjIg4XtBz2eN_jl79yOHINEUzSTqhEsHpwfThwcIOcJIcmSCE79KPjwPUaStE7837TLTTOehmBnwU6-aKwtzj9h2ehnLHQdDguAY4GhQzPB7jbvI3dq8UFx9boTvUb93YMeHBuXpok2dJxr9zgL3FrpmRRYkDrhu-6TMqsrDCjsmQUC0pFeyF11WU56QRLSYawrhHIvf_r7432U0Uwo946XaF5phmLK5qytChoQdKSRHDbMMvjvGKE1WVOS1bXweluTNiN7N8_dr3tuf4Ayqd62w), and the typescript mermaid library (v10.2.4), have been tested.

### Steps to reproduce

1. Go to [live editor](https://mermaid.live/edit#pako:eNo9UEFugzAQ_Eq0p1ZCoUBKEq5pjj1UvVWWqgWvsSWwqVlXSRF_r6Eqp9mZXc2OZoLGSYIKLoeLs4zGkhdW2I28BQr0eb3xg3IuEVCjF7Diz4pf4SbgUVhIoCffo5HRbBJ2txPAmnoSUMVRksLQsQBh53iKgd373TZQsQ-UQBgkMr0YbD32UCnsxk29SsPOb2LnUFKkE_B9WJK3ZuRo2TirTLvowXdR1szDWKXpst63hnWo943r09FIjZ7197lMy7w8YV5QeSzwuShkU2fnk8oPmZLHpyxHmOcEaP3_-lfT2lYCA9oP5_6Tzr-wm21V)
2. Define a C4 diagram with the macro `ContainerQueue_Ext`. For example:
```
C4Container
ContainerQueue_Ext(foo,"bar","baz","qux")
```
3. Observe the error:
```
Error: Lexical error on line 2. Unrecognized text.
...ContainerQueue_Ext(foo,"bar","baz","qu
---------------------^
```

## Macro "ContainerQueue_Ext"

ContainerQueue_Ext

## Macro "ContainerQueue"

ContainerQueue

### Code Sample

```text
C4Container
ContainerQueue_Ext(foo,"bar","baz","qux")
```

## Browser and Version

Chrome Version 113.0.5672.126 (Official Build) (arm64)

## Mermaid version

|ts library|online editor|
|:---:|:---:|
|10.2.4|10.2.3|

### Suggested Solutions

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by kislerdm**
## :bookmark_tabs: Summary

Fixes support of the macro `ContainerQueue_Ext` for C4 diagrams definition.

### Chores

- Trailing spaces removed
- Test covering the `Container...` macros added

Resolves #4576 

## :straight_ruler: Design Decisions

NA

### :clipboard: Tasks

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added unit/e2e tests (if appropriate)
~~:notebook: have added documentation (if appropriate)~~
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Review by sidharthv96 — APPROVED** [review]
I'm not familiar with C4. But the changes looks good to me. 
Can you add some imgSnapshotTests too?

**Review by aloisklink — APPROVED** [review]
These changes look great to me too! Thanks for adding some tests as well.

IMO, for other reviewers, the only actual changes are in these lines of JISON: https://github.com/mermaid-js/mermaid/pull/4577/commits/592e9c959be891c136cff37c67462580bd8eda59#diff-ebeabc10483d769581539e8515fcc9851825401a6ffce06e48e1114b80c68b73R170-R173

Btw, @kislerdm, it doesn't matter too much since this PR is pretty small (and Mermaid is pretty lax about commits), but it does make reviewers life easier if refactoring changes (like removing trailing spaces) are in a separate commit from bug fixes. Other than that, this PR was pretty much perfect :smile: 

---

> I'm not familiar with C4

I'm also not too familiar with C4 diagrams. @pinghe is the one who added them originally, so it might be worth waiting for a few days in case they want to give a review, but IMO, this fix is pretty small, so it should be fine!

**Comment by sidharthv96** [comment]
@aloisklink this setting was helpful for me :)

image

**Comment by aloisklink** [comment]
> @aloisklink this setting was helpful for me :)

:+1: Very cool, I didn't know GitHub added that feature! I've always used `git diff -w` since I thought GitHub didn't have that feature!

IMO, I'll probably still have to leave it off by default. I'm often looking at Python code, where whitespace matters, and GNU Makefiles, where tabs (`\t`) and spaces both do different things.

**Comment by kislerdm** [comment]
@sidharthv96 @aloisklink Hey folks! Thanks a lot for your review.

@aloisklink, you are right that the only tangible change this PR contains is the update of the JISON file :) However, I believe in "small" refactoring, hence I'd rather include trimmed spaces to PR as well if you don't mind.

@sidharthv96 could you please help me by expanding on your question? Thanks!

> Can you add some imgSnapshotTests too?

It'd enable me to execute on your suggestion.

**Comment by aloisklink** [comment]
> However, I believe in "small" refactoring, hence I'd rather include trimmed spaces to PR as well if you don't mind.

No worries, that's fine! It would have been a bit nicer to have the trimmed spaces as a separate commit in this PR, but again, it's such a small change that it doesn't really matter :smile: The mermaid project doesn't have strict commit guidelines.

> Can you add some imgSnapshotTests too?

I think @sidharthv96 would like an E2E cypress test that uses `ContainerQueue_Ext` in an `imgSnapshotTest()` in: https://github.com/mermaid-js/mermaid/blob/develop/cypress/integration/rendering/c4.spec.js

You can run these tests with `pnpm run e2e`, but they are very slow, since they run on an actual browser. Personally, since your PR is quite a small change, and already well tested, I don't think adding an `imgSnapshotTest` is necessary, but it would still be nice to have one :)

**Comment by kislerdm** [comment]
@aloisklink Thank you for clarification! I feel that the added unit tests are sufficient for the change. 

Moreover, reasonable e2e testing would require a set of decisions:
- What is the focus of the e2e test? Happy path only?
- What shall be used as a reference?
- Shall the "non external" container's colour be compared to the colour of an "external" container? For context, the external is grey, non-external is blue.

**Comment by kislerdm** [comment]
@aloisklink @sidharthv96 @knsv Hey folks! Would it possible to include the fix to upcoming release?

**Comment by aloisklink** [comment]
> Hey folks! Would it possible to include the fix to upcoming release?

Generally, Knut needs to review anything that changes a JISON file, but I think since the actual non-whitespace change is pretty minor, it might be okay to merge this without their approval. @sidharthv96, are we okay to merge without a review from @knsv?

**Comment by sidharthv96** [comment]
Knut is on vacation, so we can go ahead.

**Pull request merged**
