### PR TITLE
Added lollipop feature for updated codebase

### PR DESCRIPTION
**Pull request by may4everL**
## :bookmark_tabs: Summary
Brief description about the content of your PR.

Resolves #<your issue id here>

## :straight_ruler: Design Decisions
Describe the way your implementation works or what design decisions you made if applicable.

### :clipboard: Tasks
Make sure you
- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md) 
- [ ] :computer: have added unit/e2e tests (if appropriate) 
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by knsv** [comment]
@ashishjain0512 Could you please review this PR?

**Comment by ashishjain0512** [comment]
Hey @may4everL 

This is a great addition. One last thing  we ask you is to add a couple of test cases (rendering: under cypress/integration/rendering/classDiagram-v2) and spec (test case under src/diagrams/class/classDiagram.spec.js)

Once this is done, we will be happy to merge this.

**Comment by mestaritonttu** [comment]
@ashishjain0512 FYI there is still the unnecessary classbox surrounding the interface. So this needs a follow up patch to refactor stuff.

**Comment by may4everL** [comment]
Just noticed this branch has been merged.

As @ashishjain0512 mentioned, the surrounding classbox for the interface is redundant. I will start trying to work on that and also add some test in as needed.

**Pull request merged**
