### PR TITLE
Bug  #4691 | Arrow heads in sequence diagram

### LINKED ISSUE #4691: Improve arrow positions on sequence diagrams
### Description

Compared to most other sequence diagrams I've seen generated by other software, arrow heads in mermaid sequence diagrams are positioned differently. I would not necessarily say that the mermaid way is "wrong", but at least to my eyes it does look a bit "off" compared to what I'm used to seeing.

The largest difference is that arrow heads extend into activation boxes rather than end at the border of the box.
Also, at larger scales, the tip of the arrow heads seem to slightly shoot past the line that they point to when no activation box exist.
I have added two screenshots to illustrate how it looks now and how it might look if it was drawn like most examples I could find.

### Steps to reproduce

Link to the example used for the screenshots: [mermaid.live](https://mermaid.live/edit#pako:eNpNz1FPwyAQAOC_wu5V2lRWysrDjEYT9dU30xdsb2tjgclotDb970K7JfJAuLvvLscEtW0QJJzxa0BT42Onjk7pypBw7vuuxmS_v3m1rZHkGfvekvimpLXfRDkkox3uVhzz0T7YD0nCRUmtTKyTFpUjGi8ulJLgksvMbrUvi15kaNn8GxntsogM6IDYk6ND5TdAQaPTqmvC-lNsqMC3qLECGZ6Ncp8VVGYObjg1yuNT03nrQHo3IAU1ePs2mvoar-byfZAH1Z9D9qTMu7X6ikIIcoIfkIzxlAt2K_JMMFbwglEYQYoyFUJkZVlk5VbwmcLv0p6lO1bkebHlbCcYz4v5D_YccyI)

### Screenshots

Current look:
image

Mock-up:
image

### Code Sample

_No response_

### Setup

- Mermaid version: 10.3.0
- Browser and Version: Firefox 115.0.3

### Suggested Solutions

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mastersibin**
Resolves #4691

### CODE REVIEW

**Comment by sidharthv96** [comment]
Can you please add some screenshots of before & after and also some tests?

**Comment by mastersibin** [comment]
Before
BeforeSequence

After
AfterSequence

**Comment by sidharthv96** [comment]
image
image

The arrows don't align perfectly. We need a different approach, which solves the problem at the root.

**Comment by mastersibin** [comment]
> image image
> 
> The arrows don't align perfectly. We need a different approach, which solves the problem at the root.

I agree, its like putting a bandaid on. I'll try to find what the root cause is.

**Comment by sidharthv96** [comment]
Superseded by https://github.com/mermaid-js/mermaid/pull/4804

**Pull request closed without merging**
