### PR TITLE
Add favicon

### LINKED ISSUE #3610: Add a favicon
Add a favicon to the website

I'd love to work on it if assigned

### PR DESCRIPTION
**Pull request by PritamSarbajna**
## :bookmark_tabs: Brief description about the content of your PR.

Added a favicon to the website

Resolves #3610 

## :straight_ruler: Design Decisions

Describe the way your implementation works or what design decisions you made if applicable.

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [ ] :computer: have added unit/e2e tests (if appropriate)
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by mmorel-35** [comment]
Hi @PritamSarbajna , would it be possible to use an svg format file instead ?

**Comment by PritamSarbajna** [comment]
Hi @mmorel-35 svg is nice but it isn't supported by all browsers...do you still want it ??

**Comment by mmorel-35** [comment]
Do you have example of those browsers ?

**Comment by PritamSarbajna** [comment]
> Do you have example of those browsers ?

no 😑

**Comment by mmorel-35** [comment]
Ok, so please provide an svg file instead of all the png

**Comment by PritamSarbajna** [comment]
> Ok, so please provide an svg file instead of all the png

sure !

**Review by ParthJadhav — APPROVED** [review]

**Comment by sidharthv96** [comment]
@PritamSarbajna, please make the suggested changes.

**Comment by sidharthv96** [comment]
You could refer https://github.com/mermaid-js/mermaid-live-editor/commit/a89eb12b8cd646fd0103b35906d1a5c03313370e

**Comment by knsv** [comment]
Hey @PritamSarbajna,do you want move this foward? We are still in October!

**Comment by PritamSarbajna** [comment]
> Hey @PritamSarbajna,do you want move this foward? We are still in October!

Yeah just trying to figure out how to run this locally

**Comment by PritamSarbajna** [comment]
I can't run this locally anyone up for help ?

**Comment by sidharthv96** [comment]
Favicon is already added in https://github.com/mermaid-js/mermaid/pull/3678

**Pull request closed without merging**
