### PR TITLE
Workflow: Check if `README.md` and `docs/README.md` are in sync

### PR DESCRIPTION
**Pull request by kuanyi-ng**
## :bookmark_tabs: Summary
This PR adds a GitHub workflow that checks if `README.md` and `docs/README.md` have the same content.

This is part of issue #2456. (Documentation section)

### About workflow's triggers
In the [contribution guide](https://github.com/kuanyi-ng/mermaid/blob/develop/CONTRIBUTING.md#committing-documentation), it said that documentation-related changes can be committed directly to the `develop` branch.
So I made this workflow to target `push` and `pull_request` events for both `master` and `develop` branches.

### Possible improvements (for another PR)
1. Output which `README.md` is newer so it's easier to sync both `README.md` files.
  a. still don't have a concrete idea on how to determine if one `README.md` is newer than the other
  a. this information might be available from `git log` or `git blame`
2. Sync the content of `README.md` and `docs/README.md` as a part of the workflow.
  a. it might be possible to automatically apply the changes to either one of the READMEs. 
3. Also check if `CHANGELOG.md` and `docs/CHANGELOG.md` have the same content.

### :clipboard: Tasks
Make sure you
- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md) 
- [ ] :computer: have added unit/e2e tests (if appropriate) 
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Review by ashishjain0512 — APPROVED** [review]
Thank you that's super userful!

**Comment by mmorel-35** [comment]
Why merging this if the new workflow doesn't pass?
Now every PR on the master is going to fail

**Comment by kuanyi-ng** [comment]
> Why merging this if the new workflow doesn't pass? Now every PR on the master is going to fail

@mmorel-35 
Sorry for not making sure the workflow will pass before this PR is merged.
Following are a few solutions to this situation:
1. Revert this PR → Sync `README.md` and re-adding this workflow in one PR
2. Sync `README.md` in another PR (without reverting this PR)

Assuming that syncing both `README.md` will take up some time, I think reverting this PR is better for the moment.
What do you think?

**Comment by mmorel-35** [comment]
I prefer the second option, this feature is great. The synchronisation just need to be fixed

**Comment by kuanyi-ng** [comment]
I'm afraid I don't know much about `mermaid.js` to proceed with the second option. (Just found out about `mermaid.js` last week. Are there any guidelines that I can follow while syncing both `README.md`?

**Comment by Yash-Singh1** [comment]
There will be some road bumps when doing this:

1. Ensure if we need the CI checks in the documentation header.
2. Make sure the images for the Mermaid.js diagrams should appear in the README and documentation (README should use different code fence names than documentation)
3. Sync links between README and docs without having any resolving problems as they exist in different in different directories

**Pull request merged**
