### PR TITLE
feat: add name field to the actors

### PR DESCRIPTION
**Pull request by ad1992**
## :bookmark_tabs: Summary

- [x] The actors have unique names so adding a `name` field to the actors for easier identification in SVG nodes.
- [x] Added a actor type actor example as there is none in `sequence.html`

```
<rect x="0" y="0" fill="#eaeaea" stroke="#666" width="150" height="65" name="Alice" rx="3" ry="3" class="actor actor-top"></rect>
```

cc @sidharthv96 

## :straight_ruler: Design Decisions

The final goal is to make the overall API better as mentioned in https://github.com/mermaid-js/mermaid/pull/5017#issuecomment-1941554807, this is an alternative to get the attributes easily from `svg` since right now there is no way to identify both actor nodes belonging to one particular actor as there is no unique identifier. Hence I am adding a `name` identifier so the nodes can be identified in SVG easily as well.

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [ ] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/contributing.md#update-documentation) is used for all new features.
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by ad1992** [comment]
@sidharthv96 friendly reminder :)

**Comment by ad1992** [comment]
Any update on this PR?

**Comment by sidharthv96** [comment]
Was really busy. This should be out in 10.9.0 soon.

**Comment by ad1992** [comment]
Awesome thanks @sidharthv96

**Pull request merged**
