### PR TITLE
Changes to Gantt Parsers to allow hashes and semicolons to titles, sections, and task data.

### LINKED ISSUE #1981: Unable to use # or ; in gantt diagram
this doesn't work 

```
gantt
    title HASHTEST
THIS#HASH  :2021-04-03 11:06:07, 2sec
```
escaping is also not possible not quoting the text

Just put a # or ; in the THISHASH and you can see the parsing error

https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ2FudHRcbiAgICB0aXRsZSBIQVNIVEVTVFxuVEhJU0hBU0ggIDoyMDIxLTA0LTAzIDExOjA2OjA3LCAyc2VjIiwibWVybWFpZCI6e30sInVwZGF0ZUVkaXRvciI6ZmFsc2V9

thanks

### PR DESCRIPTION
**Pull request by FutzMonitor**
## :bookmark_tabs: Summary

This PR makes changes to the `gantt.jison` file that allows users to use hash and semicolons in the title, section, and task title. 

Resolves #1981

## :straight_ruler: Design Decisions

 Changes to gnatt.jison
1. Removed the hash and semicolon symbols from the title regex to allow for their use.
2. Removed the hash and semicolon symbols from the section regex to allow fortheir use.
3. Removed the hash and semicolon symbols for the taskTxt regex to allow for their use. I did not remove the colon because the parser fails to recognize when the actual taskData begins if that distinctions isn't kept.
4. Removed the regex \#[^\n]* which skipped comments to fix some bugs with hash symbols in the taskTxt. I tested this changed by putting it back and using the  comment `## hello world` to see if it was recognized as a comment, but I would receive a syntax error and the diagram would not be rendered. So, I think we can safely remove that line, BUT it would be best practice if someone else tested this change to ensure that this will not break anyone's Gantt diagrams."

### :clipboard: Tasks

Make sure you

- [ ] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [ ] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/development.md#3-update-documentation) is used for all new features.
- [ ] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by FutzMonitor** [comment]
When you use `#` in the live editor, it doesn't break the live editor. However, I believe we have to make this functionality visually consistent to `%%` by styling the text green and making sure. 

These changes should be followed with updates to the renderer because there's no mention of this functionality there [[link](https://mermaid.js.org/syntax/gantt.html#comments)].

**Review by nirname — APPROVED** [review]
LGTM

**Review by sidharthv96 — CHANGES_REQUESTED** [review]
Please add unit tests and rendering tests for the newly supported cases, along with updates to the documentation.

**Comment by FutzMonitor** [comment]
Sounds good. I'll look at the other tests for guidance and update affected documentation.

**Review by FutzMonitor — COMMENTED** [review]
I added some unit tests and rendering tests. I looked through the documentation, and I didn't find any explicit instances mentioning that semicolons and hashtags weren't allowed. So, I didn't add anything in terms of documentation. I did add another graph in `gantt.html` to demonstrate the semicolons and hashtags are fine.

**Pull request merged**
