### PR TITLE
add the way to add notes to class diagram

### LINKED ISSUE #1414: Is it possible to add notes on a class diagram?
Hi,

Notes on a class diagram are very useful to convey some important design details. Unfortunately, I couldn't figure out, how can I add notes on a class diagram. Is it possible at all with mermaid?

Thanks!

### PR DESCRIPTION
**Pull request by DKurilo**
## :bookmark_tabs: Summary

It adds the way to add notes to class diagram.
The way it works:
for lines:
```
note "I love this diagram!\nDo you love it?"
```
it adds one more vertex that is not related to anything.
for lines:
```
note for Class10 "Cool class\nI said it's very cool class!"
```
it adds vertex that has relation with Class10 vertex.
Relation is presented as dotted line and this is okay for UML.

Also this PR fixes class diagram with `darge-d3` renderer. For some reason it was broken.

More information is here: https://github.com/mermaid-js/mermaid/issues/1414#issuecomment-1273960484 

Resolves #1414 

## :straight_ruler: Design Decisions

As I wrote before, notes are one more graph vertex. This is only one decision.

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added unit/e2e tests (if appropriate)
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by DKurilo** [comment]
Are some maintainers there?
Can you, please, at least answer something?

**Review by sidharthv96 — APPROVED** [review]
LGTM overall, but as there are significant changes, need reviews from @knsv or @ashishjain0512 or any other maintainer who has knowledge in this area.

**Comment by sidharthv96** [comment]
@DKurilo, if there is any `it.only`, I believe it should be removed. 
Can you also add https://www.npmjs.com/package/eslint-plugin-no-only-tests so that we don't accidentally check in `only` tests?

**Comment by DKurilo** [comment]
@sidharthv96 , I created this PR:
https://github.com/mermaid-js/mermaid/pull/3690

**Pull request merged**
