### PR TITLE
fix: De-duplicates dependencies

### LINKED ISSUE #3166: Duplicate dependencies bloating bundle size
**Describe the bug**

Many of the `d3-` dependencies have become duplicated with multiple versions of each contained in the bundle. I believe it's because `dagre-d3` still has a strict dependency on an old version of `d3`.

**To Reproduce**

See the committed `yarn.lock` file on default branch, eg:

https://github.com/mermaid-js/mermaid/blob/develop/yarn.lock#L4349-L4384

### PR DESCRIPTION
**Pull request by tommoor**
## :bookmark_tabs: Summary

Removes over 50 duplicate dependencies by specifying yarn resolutions for [dagre-d3](https://www.npmjs.com/package/dagre-d3) which hasn't been updated in 3 years.

Resolves #3166

### :clipboard: Tasks
Make sure you
- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md) 
- [ ] :computer: have added unit/e2e tests (if appropriate) 
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Review by sidharthv96 — APPROVED** [review]
image

image

There is ~8.3% reduction in the minimized files and all our tests pass. LGTM.

**Review by mmorel-35 — APPROVED** [review]

**Comment by tommoor** [comment]
I'm not a collaborator so will need someone else to hit merge and release

**Comment by tommoor** [comment]
Hey folks, just wanted to let you know that 9.3.0 was much smaller but the build size immediately went back again in 9.4.0.

image

https://bundlephobia.com/package/mermaid@9.3.0

**Comment by sidharthv96** [comment]
image
 
Seems like elk is the culprit. But elk will only be loaded if necessary. So it shouldn't affect most users. Will investigate.

**Comment by sidharthv96** [comment]
@tommoor size is back down in 9.4.2-rc.1
The actual size is much smaller as elk and cytoscape are dynamic imports which are only used if the corresponding diagram is loaded.

image

**Pull request merged**
