### PR TITLE
Set text color for flowchart link labels according to linkStyle definitions

### LINKED ISSUE #962: How to style the text on the line?
It seems the LINKSTYLE is only able to style the line, but not able to style the arrow and the text associated with it.  How to style the text and arrow of a line?

### PR DESCRIPTION
**Pull request by GDFaber**
## :bookmark_tabs: Summary
The link label text can be colored by using `color` settings in the `linkStyle` definition.

Resolves #962

## :straight_ruler: Design Decisions
Applied color settings to edge label style. Extended the tests for label text color (dist/index.html and cypress integration test) and linkStyle example in the docs.

### :clipboard: Tasks
Make sure you
- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md) 
- [x] :computer: have added unit/e2e tests (if appropriate) 
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by GDFaber** [comment]
This is not ready yet, I'll move the styleFromStyleArr function to utils.js and modify it to return style and labelStyle in one go so it doesn't need to go through all settings twice.

**Comment by GDFaber** [comment]
Done, it should be complete now.

**Comment by GDFaber** [comment]
Done.

**Comment by SR--** [comment]
I cannot change either the link text label or the background of that text with this, here is the [editor](https://mermaid-js.github.io/mermaid-live-editor/edit/#eyJjb2RlIjoiZ3JhcGggVERcbiAgICBBW0NocmlzdG1hc10gLS0-fEdldCBtb25leXwgQihHbyBzaG9wcGluZylcbiAgICBCIC0tPiBDe0xldCBtZSB0aGlua31cbiAgICBDIC0tPnxPbmV8IERbTGFwdG9wXVxuICAgIEMgLS0-fFR3b3wgRVtpUGhvbmVdXG4gICAgQyAtLT58VGhyZWV8IEZbZmE6ZmEtY2FyIENhcl1cbiAgICBsaW5rU3R5bGUgZGVmYXVsdCBmaWxsOm5vbmUsc3Ryb2tlOmdyZWVuLGNvbG9yOnJlZDsiLCJtZXJtYWlkIjoie1xuICBcInRoZW1lXCI6IFwiZGVmYXVsdFwiXG59IiwidXBkYXRlRWRpdG9yIjp0cnVlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6dHJ1ZX0). What am I missing?

**Pull request merged**
