### PR TITLE
Gantt: add top xaxis

### PR DESCRIPTION
**Pull request by nacc**
## :bookmark_tabs: Summary
Add a top x-axis to Gantt charts that mirrors the bottom x-axis

## :straight_ruler: Design Decisions
Straightforward copy and paste of existing code.

### :clipboard: Tasks
Make sure you
- [X] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md) 
- [X] :computer: have added unit/e2e tests (if appropriate) 
- [X] :bookmark: targeted `develop` branch

### CODE REVIEW

**Review by knsv — CHANGES_REQUESTED** [review]
Thanks @nacc, this look great!

There are one thing that would make this even better. The feature need an on on/off switch similar to mirrorActors in sequence diagrams. Two things that we need to do:
1. Add this in the configuration options so that it possible to turn is on/off on a site level when you add Mermaid
2. Add a topAxis directive which will make it possible to turn on topAxis even if the site confiuration as topAxis as off

Is the on/off switch something you could help with?

Thanks again
/Knut

**Comment by nacc** [comment]
@knsv yep I can do that. I'll update the PR today!

**Comment by nacc** [comment]
I *think* my branch has the changes requested correctly. I'm not a JS person at all, so please point me in a corrected direction if I did something wrong :)

**Comment by knsv** [comment]
Thanks will review this PR today.

**Comment by knsv** [comment]
Hello! I am reviewing this now. I tested it in my local development environment and the top axis is not coming at the top for me:
image

Did something go wrong?

This is the html file I used:
```
<html>
  <head>
    <link
      href="https://fonts.googleapis.com/css?family=Montserrat&display=swap"
      rel="stylesheet"
    />
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+SC&display=swap" rel="stylesheet">
    <style>
      body {
        /* background: rgb(221, 208, 208); */
        /* background:#333; */
        font-family: 'Arial';
        }
      h1 { color: grey;}
      .mermaid2 {
        display: none;
      }
      .mermaid svg {
        font-size: 12px !important;
      }
    </style>
  </head>
  <body>
    <h1>info below</h1>
    <div class="flex">

      <div class="mermaid" style="width: 100%; height: 20%;">
gantt
      dateFormat  YYYY-MM-DD
      axisFormat  %d/%m
      title Adding GANTT diagram to mermaid
      excludes weekdays 2014-01-10

      section A section
      Completed task            :done,    des1, 2014-01-06,2014-01-08
      Active task               :active,  des2, 2014-01-09, 3d

      </div>
        <script src="./mermaid.js"></script>
    <script>
      mermaid.parseError = function (err, hash) {
        };
      mermaid.initialize({
        logLevel: 0,
        flowchart: { nodeSpacing: 10, curve: 'cardinal', htmlLabels: false },
        htmlLabels: false,
        sequence: { actorFontFamily: 'courier',actorMargin: 50, showSequenceNumbers: false },
        fontFamily: '"arial", sans-serif',
        fontFamily: 'courier',
        curve: 'cardinal',
        securityLevel: 'loose',
        gantt:{topAxis: true}
      });
      function callback(){alert('It worked');}
    </script>
  </body>
</html>
```

**Comment by nacc** [comment]
Urgh, I see the problem, it was my misunderstanding of what hte translate method did. Fix incoming!

**Comment by nacc** [comment]
Can you try with the fixlet I just pushed?

**Comment by nacc** [comment]
@knsv the failure seems unrelated to my changes, from something in a different diagram type?

**Comment by nacc** [comment]
(trying to rebase now)

**Comment by knsv** [comment]
will give it a spin!

**Comment by knsv** [comment]
I tried this again and it getting closer. The axis is at the top of the diagram.
image

The problem is caused by
image

Any reason why you have that there or should I just remove it?

**Comment by nacc** [comment]
> I tried this again and it is getting closer. The axis is at the top of the diagram.
> image
> 
> The problem is caused by
> image
> 
> Any reason why you have that there or should I just remove it?

Ah ha! Probably c&p failure on my part. Definitely can be removed or possibly will need adjusting to `-1em`? I'm treating the top axis like a mirror of the bottom, ideally.

**Comment by knsv** [comment]
Ok, then I think this one is ready. I will remove that line and merge it! Thanks

**Pull request merged**
