### PR TITLE
Documentation for #2509

### LINKED ISSUE #2509: subgraph direction not applying
**Describe the bug**
The subgraph direction features doesn't work anymore

**To Reproduce**
1. Create a graph
2. Add subgraphs with different directions

**Expected behavior**
subgraph should have different directions then the main graph

**Screenshots**
image

**Code Sample**
[live editor](https://mermaid.live/edit#eyJjb2RlIjoiZmxvd2NoYXJ0XG4gICAgc3ViZ3JhcGggRmxvd1xuICAgICAgICBkaXJlY3Rpb24gTFJcbiAgICAgICAgQSAtLT4gQlxuICAgICAgICBCIC0tPiBDXG4gICAgZW5kXG4gICAgc3ViZ3JhcGggQVBJXG4gICAgICAgIGRpcmVjdGlvbiBCVFxuICAgICAgICBDIC0tPiBEe1NvbWV0aGluZyA_fVxuICAgICAgICBEIC0tIFllcyAtLT4gRVxuICAgICAgICBEIC0tIE5vIC0tPiBGXG4gICAgICAgIEUgLS0-IEdcbiAgICBlbmQiLCJtZXJtYWlkIjoie1xuICBcInRoZW1lXCI6IFwiZGVmYXVsdFwiXG59IiwidXBkYXRlRWRpdG9yIjpmYWxzZSwiYXV0b1N5bmMiOnRydWUsInVwZGF0ZURpYWdyYW0iOmZhbHNlfQ).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 96.0.4664.45

**Additional context**
Feature merge with following PR: https://github.com/mermaid-js/mermaid/pull/2271

### PR DESCRIPTION
**Pull request by jason-curtis**
## :bookmark_tabs: Summary

Since #2509 is unlikely to be solved soon I'm adding some documentation. This should at least make the behavior less surprising.

I don't think it actually resolves #2509 but since this is expected behavior per @knsv ([here](https://github.com/mermaid-js/mermaid/issues/2509#issuecomment-1258180439)) maybe #2509 can be recategorized as a feature request.

## :straight_ruler: Design Decisions

Nothing surprising here. I included an illustrative example.

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added necessary unit/e2e tests.
  - (N/A - documentation only)
- [x] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/development.md#3-update-documentation) is used for all new features.
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by sidharthv96** [comment]
@jason-curtis can you run prettier to fix the formatting issues?

https://mermaid.js.org/community/development.html#contributing-documentation

**Comment by jason-curtis** [comment]
@sidharthv96 It's hard to see how these lint errors could be from my change. I don't see any mention of `prettier` in the documentation you sent, so maybe something is missing?.

I'll try running prettier and see what happens.

**Comment by sidharthv96** [comment]
Prettier is run automatically when you commit locally, once you have run `pnpm install`. 
Committing locally would also build the docs and inject that into the PR.

**Comment by jason-curtis** [comment]
ah I see the prettier issue now. I didn't see the `[warn] packages/mermaid/src/docs/syntax/flowchart.md` amidst all of the yellow eslint warnings!

I've been trying to get everything to install and build cleanly on a fresh GH codespace, no luck so far.

```bash
curl https://get.volta.sh | bash
# (restart terminal here)
volta install node
npx pnpm install # yes, install pnpm
# ^ this command fails.
```
Here's a full gist of the 2nd terminal session: https://gist.github.com/jason-curtis/746affa2385639c8fd2ea3c0332c70e3
It looks like the error is:
```bash
packages/mermaid/src/setupGraphViewbox.js (2:9) "SVG" is not exported by "packages/mermaid/src/diagram-api/types.ts", imported by "packages/mermaid/src/setupGraphViewbox.js".
```

At this point the package is at least partially installed, so I may be able to bash through by manually running prettier (already did this in #ef8b75a ) and the docs build (I'll try this next).

**Comment by jason-curtis** [comment]
OK, I was able to manually run `npx pnpm --filter mermaid run docs:build` as suggested in the [latest failed job](https://github.com/mermaid-js/mermaid/actions/runs/5886463258/job/15964363567?pr=4740) so hopefully that'll cover it!

It looks like things are pretty OK in my latest codespace despite the error when running `npx pnpm install` - I guess it came close enough to completing the install properly!

**Comment by sidharthv96** [comment]
@jason-curtis thank you! I'll fix the SVG error.

**Comment by sidharthv96** [comment]
Yeah, the final step of install is the build, which failed due to the SVG bug. 
But prettier and docs don't really need that.

**Pull request merged**
