### PR TITLE
Docs: update Ecosystem section

### PR DESCRIPTION
**Pull request by huynhicode**
## :bookmark_tabs: Summary

This PR updates the [Ecosystem](https://mermaid.js.org/ecosystem/integrations.html) section of the Mermaid JS docs.

Updates:

- add "Mermaid Chart" page
- separate Integrations page into two pages ("Integrations - community" and "Integrations - create")
- remove "Showcase" page
- minor verbiage updates
- content formatting

As a follow-up to this PR, it would be nice to add descriptions to the list of community plugins/integrations as not everyone who views the list will have knowledge about all the tools/technologies.

Also, a check to make sure all links are current.

Resolves # n/a

## :straight_ruler: Design Decisions

Design decisions come from within the Mermaid Chart org.

## Screenshots:

Screenshot 2023-09-06 at 10 13 30 PM

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [ ] :computer: have added necessary unit/e2e tests.
- [ ] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/development.md#3-update-documentation) is used for all new features.
- [ ] :bookmark: targeted `develop` branch

### CODE REVIEW

**Review by knsv — APPROVED** [review]
This looks great! Thank you Steph!

**Review by sidharthv96 — CHANGES_REQUESTED** [review]
Please add the changed urls here so that old links don't break.

https://github.com/mermaid-js/mermaid/blob/07f460a1846d22e54016c25862b9eb42642583ef/packages/mermaid/src/docs/.vitepress/theme/redirect.ts#L85-L93

**Comment by huynhicode** [comment]
> Please add the changed urls here so that old links don't break.
> 
> https://github.com/mermaid-js/mermaid/blob/07f460a1846d22e54016c25862b9eb42642583ef/packages/mermaid/src/docs/.vitepress/theme/redirect.ts#L85-L93

Done - thanks!

**Comment by sidharthv96** [comment]
@huynhicode, as showcases was removed, that should also be added to the redirect.

**Comment by huynhicode** [comment]
> @huynhicode, as showcases was removed, that should also be added to the redirect.

Done, thanks!

**Pull request merged**
