### PR TITLE
Auto transform `mermaid-example` in docs.

### LINKED ISSUE #3315: Update examples in docs
Currently, the examples in the docs folder used on github and the examples on the docs site have different formats. This leads to users on github browsing into the docs folder without seeing the diagrams or broken examples in the docs site.

This should be fixed. So that the md files renders both on github and using docsify.

relates to #3291 
@jvaque

### PR DESCRIPTION
**Pull request by sidharthv96**
## :bookmark_tabs: Summary
`mermaid-example` blocks were not rendered in GitHub. 
Added a build step for docs which adds a `mermaid` block for each `mermaid-example`, so that it's rendered in Github.

image

If anyone makes manual changes to `docs`, lint will fail indicating what to do.

Resolves #3315

## :straight_ruler: Design Decisions
By parsing the AST and injecting directly, it will work for any complex structure.
We could also introduce grammar & spell checks to docs in future easily.

### :clipboard: Tasks
Make sure you
- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md) 
- [ ] :computer: have added unit/e2e tests (if appropriate) 
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by sidharthv96** [comment]
image

Collapsing both docs folder will help for an easy review.

**Comment by sidharthv96** [comment]
@weedySeaDragon @dbartholomae, https://danger.systems/js/ seems like a good choice to integrate some additional checks. Have you worked with anything better, or should we go ahead with danger?

**Comment by dbartholomae** [comment]
I haven't worked with danger yet, but heard good things, so I don't see a reason not to go ahead with it.
I've used two different methods so far:
1. A simple 4-line bash script in a separate workflow that is triggered on merge to `main`, runs the build script (first line) and then adds/commits/pushes (the other three lines).
2. Building and committing changed docs as part of a `semantic-release` process, see e.g. [this repo](https://github.com/dbartholomae/middy-middleware-jwt-auth/blob/main/release.config.js#L9).

Running the build on push to main instead of running it on PR change has the advantage that it doesn't run over and over when there are stil discussions and changes going on. The disadvantage is that it's possible for a PR to change the output files only without realizing that this will be overwritten right after merge.

**Comment by sidharthv96** [comment]
Will need some work after #3408 is merged.

**Comment by sidharthv96** [comment]
> The disadvantage is that it's possible for a PR to change the output files only without realizing that this will be overwritten right after merge.

@dbartholomae this is exactly why the current CI fails if there is any difference.

>  it doesn't run over and over when there are stil discussions and changes going on.

As the current doc lint takes only 7 seconds extra, I think it's a valid tradeoff.

**Comment by sidharthv96** [comment]
> The disadvantage is that it's possible for a PR to change the output files only without realizing that this will be overwritten right after merge.

**Review by knsv — APPROVED** [review]
Looks great! Hopefully this will improve readability on GitHub without making the docs side hard to maintain!

**Comment by weedySeaDragon** [comment]
(Realize this has been closed)
Sorry I didn't have a chance to comment.  This is a good step forward.

**Comment by sidharthv96** [comment]
@weedySeaDragon we merged this as we had multiple PRs that might conflict with this. 

We'll be doing the rest of the work in a new, (hopefully smaller) PR.

**Comment by CalebUsadi** [comment]
This process seems to add unnecessary complexity to the documentation. It complicates the build and development process; contrary to [contributing.md](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md), `docsify serve docs` does not allow for live reloading of the server, because modifications to `src/docs` don't update the live server; the "edit this page" link in any documentation page doesn't actually open to the editable file and displays a harsh, inaccessible warning; the repo contains significant redundant code and extra files to support the build process. The only advantage is the elimination of redundant code chunks in the documentation, which does not outweigh the drawbacks. I would  like to reopen this issue and refactor the documentation, which I will do in a branch I create.

**Comment by sidharthv96** [comment]
There is a complete documentation overhaul going on in https://github.com/mermaid-js/mermaid/pull/3678

I understand the main concerns are:

1. Absence of live update (need to fix)
2. Edit page link is wrong (fixed in https://github.com/mermaid-js/mermaid/pull/3612)
3. Redundant code

**Comment by CalebUsadi** [comment]
Thank you!

**Pull request merged**
