### PR TITLE
Tidy up contribute to docs page

### PR DESCRIPTION
**Pull request by Encr1pt0r**
## Summary

Updated headings and more bullet points for improved readability

Resolves "Revise Contributing Documentation section" in #2910

## What's been done and why

image

More headings that bring out more clarity to the reader

image

Use of bullet point lists instead of paragraphs to break down information 

image

Use of bold and line separators to separate information

### CODE REVIEW

**Comment by nirname** [comment]
Any updates on this one?

**Comment by nirname** [comment]
@Encr1pt0r Hi! Any plans to continue this one?

**Comment by Encr1pt0r** [comment]
> @Encr1pt0r Hi! Any plans to continue this one?

Hi and yes, as long as its approved it can be done

**Comment by nirname** [comment]
@Encr1pt0r I was asking about status of it some time ago, probably you missed it. Because I didn't get quick response I started to prepare another documentation update #5132 which basically absorbs yours. I thought this had been abandoned. May be it would be better to check mine and comment on it?

**Pull request closed without merging**
