### PR TITLE
Pin Node.JS version in GitHub Actions/Netlify to v18.18.2 using NVM (removes volta)

### PR DESCRIPTION
**Pull request by aloisklink**
## :bookmark_tabs: Summary

Pin our Node.JS version to v18.18.2 using NVM.

This is important as our Netlify builds have recently stopped working, see https://app.netlify.com/sites/mermaid-js/deploys/656b6ffb3872da00082fda6f.

This is because [Node.JS v18.19.0 came out on 2023-11-29](https://nodejs.org/en/blog/release/v18.19.0) and Netlify recently switched to using it. This version of Node.JS is incompatible with `ts-node-esm`, which is used for our build script, see  https://github.com/TypeStrong/ts-node/issues/2094.

Because of this, we need to tell Netlify to use Node.JS v18.18.2, which can be done by setting a `.nvmrc` file, see https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript.

I've also told GitHub Actions to use Node.JS v18.18.2, since although they're still cached on that version, they'll soon upgrade to v18.19.0.

### Why am I switching from `volta` to `nvm`

Currently, we're using [volta](https://github.com/volta-cli/volta) to manage our Node.JS version. Unfortunately, Volta isn't as compatible with CI (netlify/GitHub Actions), so I've moved to NVM.

### netlify build log error

For posterity, the error message from netlify's build logs is:

```
5:57:39 PM: Now using node v18.19.0 (npm v10.2.3)
[...REMOVED UNNECESSARY LINES...]
5:57:50 PM: . prepare: > ts-node-esm --transpileOnly .vite/build.ts
5:57:51 PM: Failed during stage "Install dependencies": dependency_installation script returned non-zero exit code: 1
5:57:51 PM: . prepare: TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /opt/build/repo/.vite/build.ts
5:57:51 PM: . prepare:     at new NodeError (node:internal/errors:405:5)
5:57:51 PM: . prepare:     at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:136:11)
5:57:51 PM: . prepare:     at defaultGetFormat (node:internal/modules/esm/get_format:182:36)
5:57:51 PM: . prepare:     at defaultLoad (node:internal/modules/esm/load:101:20)
5:57:51 PM: . prepare:     at nextLoad (node:internal/modules/esm/hooks:864:28)
5:57:51 PM: . prepare:     at load (/opt/build/repo/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.17.5_typescript@5.1.6/node_modules/ts-node/dist/child/child-loader.js:19:122)
5:57:51 PM: . prepare:     at nextLoad (node:internal/modules/esm/hooks:864:28)
5:57:51 PM: . prepare:     at Hooks.load (node:internal/modules/esm/hooks:447:26)
5:57:51 PM: . prepare:     at MessagePort.handleMessage (node:internal/modules/esm/worker:196:24)
5:57:51 PM: . prepare:     at [nodejs.internal.kHybridDispatch] (node:internal/event_target:786:20) {
5:57:51 PM: . prepare:   code: "ERR_UNKNOWN_FILE_EXTENSION"
```

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added necessary unit/e2e tests.
- [x] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/development.md#3-update-documentation) is used for all new features.
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Review by sidharthv96 — COMMENTED** [review]
Can't we use pnpm itself to manage node? https://pnpm.io/cli/env
That would mean one less tool. 

Netlify is currently working as I set the NODE_VERSION environment variable in netlify.

**Comment by aloisklink** [comment]
> Can't we use pnpm itself to manage node? https://pnpm.io/cli/env

Yep, we could, but then what tool would we use to manage `pnpm`? I believe we're currently using [corepack (Node.JS's built-in version manager for yarn/pnpm)](https://nodejs.org/api/corepack.html) to automatically install/update pnpm: https://github.com/mermaid-js/mermaid/blob/798f9f8b78381caf63628e4b20151de8b3f0d65a/package.json#L7.

It's also not as nice as just using the following in GitHub Actions:

```yaml
  - name: Setup Node.js
    uses: actions/setup-node@v4
    with:
      cache: pnpm
      node-version-file: '.nvmrc'
```

> Netlify is currently working as I set the `NODE_VERSION` environment variable in netlify.

:rocket: Awesome! In that case, this PR isn't urgent (yet).

Maybe a better way of fixing this issue would be to switch to using https://www.npmjs.com/package/tsx instead of `ts-node-esm`. Or we could try `ts-node-esm`'s v11 beta release too. I can have a look this evening.

**Comment by sidharthv96** [comment]
I remember having some problems after switching to tsx. Don't recall the exact issue. Maybe it's fixed now.

**Comment by aloisklink** [comment]
> I remember having some problems after switching to tsx. Don't recall the exact issue. Maybe it's fixed now.

I've made a PR for replacing `ts-node-esm` with `tsx` that will also close this PR and it all seems to work, see https://github.com/mermaid-js/mermaid/pull/5104. If you're talking about https://github.com/mermaid-js/mermaid/commit/75337287ea000d76cd835181cb7395d467271ea3, I think it's just because we forgot to remove the `--transpileOnly` flag, but :shrug:, it's entirely possible that ESBuild was missing some TypeScript features that we use.

**Pull request closed without merging**
