### PR TITLE
Chore: Typo fixed in multiple files

### PR DESCRIPTION
**Pull request by SusheelThapa**
## :bookmark_tabs: Summary

This PR fix the typo that was made in multiple files

```pseudo
Descision > Decision
ot > to
mantained > maintained
verion > version
alway > always
```

### :clipboard: Tasks

Make sure you

- [X] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [X] :computer: have added necessary unit/e2e tests.
- [X] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/development.md#3-update-documentation) is used for all new features.
- [X] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by sidharthv96** [comment]
Please resolve the conflicts.

**Comment by SusheelThapa** [comment]
@sidharthv96 I have review conflict.

**Comment by sidharthv96** [comment]
Please edit the correct source file. You can find the location at the top of the file you've edited.

**Comment by SusheelThapa** [comment]
> Please edit the correct source file. You can find the location at the top of the file you've edited.

I didnot get you. There is no merge conflict except the following by github action:

image

And I have no idea over it.

**Pull request merged**
