### PR TITLE
sequenceDiagram.md += previews under snippets

### PR DESCRIPTION
**Pull request by gwpl**
## :bookmark_tabs: Summary
Brief description about the content of your PR.

Resolves #<your issue id here>

## :straight_ruler: Design Decisions
Describe the way your implementation works or what design decisions you made if applicable.

### :clipboard: Tasks
Make sure you
- [ ] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md) 
- [ ] :computer: have added unit/e2e tests (if appropriate) 
- [ ] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by Yash-Singh1** [comment]
`mermaid-example` already adds the preview and the code: https://github.com/mermaid-js/mermaid/blob/develop/docs/index.html#L102.

**Comment by gwpl** [comment]
I was reading directly from github:
https://github.com/mermaid-js/mermaid/blob/develop/docs/stateDiagram.md
and here is DOES NOT produce preview.

IIUC github/gitlab they are using mermaid code - maybe something has to be fixed in that manner to make `marmaid-example` work also on those platforms ?

**Comment by knsv** [comment]
I agree that it would be nice to having it look good at both places!

**Comment by Yash-Singh1** [comment]
> I agree that it would be nice to having it look good at both places!

Yes, but the problem is that it will duplicate the previews in the official docs.

**Comment by sidharthv96** [comment]
Closed in #3401

**Pull request closed without merging**
