### PR TITLE
Gantt: Added multiple dependencies syntax

### LINKED ISSUE #552: Feature request: Gantt chart task with multiple dependencies
There are cases in a project when multiple tasks has to be ready (apple *and* banana) in order to start with a given task (cherry).

```mermaid
gantt
  apple :a, 2017-07-20, 1w
  banana :crit, b, 2017-07-23, 1d
  cherry :active, c, after b, after a, 1d
```

It would be intuitive if I could just express these dependencies by adding multiple `after` properties to the task.

Is there a way I can workaround this missing feature at the moment? If either start time or duration changes on apple and banana, I need to remember to update cherry to depend on the one with the latest end time.

### PR DESCRIPTION
**Pull request by itprdev**
Usage:
```
gantt
  apple :a, 2017-07-20, 1w
  banana :crit, b, 2017-07-23, 1d
  cherry :active, c, after b a, 1d
```
Separated by space

Resolves #552

### CODE REVIEW

**Comment by Dunning-Kruger** [comment]
Hey, don't forget to add tests for the feature you developed! More information can be found in our [contribution guide](https://github.com/mermaid-js/mermaid/blob/master/CONTRIBUTING.md).

**Comment by Dunning-Kruger** [comment]
Sorry for the double comment. Don't forget to target the `develop` branch!

**Comment by itprdev** [comment]
> Sorry for the double comment. Don't forget to target the `develop` branch!

In that case should I delete this commit and start a new one on develop branch or can I somehow update the existing one?

**Comment by Dunning-Kruger** [comment]
@itprdev You can edit the target branch at the top of the pull request. Here's [a guide](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request) if you can't find the button but I'm sure you'll have no problem.

**Comment by itprdev** [comment]
> Thank you very much for your contribution. Don't forget to add tests for the feature you developed! More information can be found in our [contribution guide](https://github.com/mermaid-js/mermaid/blob/master/CONTRIBUTING.md).

Could you elaborate on the tests? 
And where can I find more info about tests. Looked through contribution doc but couldnt comprehend it in full.

**Comment by Dunning-Kruger** [comment]
> Could you elaborate on the tests?
> And where can I find more info about tests. Looked through contribution doc but couldnt comprehend it in full.

@itprdev Tests in mermaid come in two flavors: unit tests & e2e. 

You can find the existing unit tests for gantts in [`/src/diagrams/gantt/ganttDb.spec.js`](https://github.com/mermaid-js/mermaid/blob/master/src/diagrams/gantt/ganttDb.spec.js) and the existing e2e tests in [`/cypress/integration/rendering/gantt.spec.js`](https://github.com/mermaid-js/mermaid/blob/master/cypress/integration/rendering/gantt.spec.js)

**Unit tests,** very basically, make sure that the parsing is done correctly. That the code you wrote is correct and the expected result comes out. This allows you to "prove" that what you wrote works and future developers to know that they did not break this feature of the library by adding whatever they added.

In your case, for example, your code parses multiple tasks declared as dependencies and picks the latest end datetime of those to use as start datetime. So, you could write a basic test for that by giving it the markdown for a gantt chart where a task declares multiple dependencies and make sure the parser picks the correct "start datetime" for your task.

**E2E tests**, again very basically, make sure that the render of graphs does not change through different versions (or that the changes are easily visible and "accepted" before merging). They basically work by generating a graph, taking a screenshot and comparing it to a previous store screenshot. You can add a new e2e test that contains a task with multiple dependencies, or improve the current existing one to include a task with multiple dependencies.

I hope it helps!

**Comment by Dunning-Kruger** [comment]
I did not mention but... just in case: both concepts (unit & e2e) are pretty universal in software development. So you can always google them to learn what "good" tests (of those types) are, what they usually attempt to achieve, etc, at a "generic" level. Of course, implementation varies from project to project, framework to framework, language to language, etc etc.

**Comment by chris579** [comment]
> @itprdev You can edit the target branch at the top of the pull request. Here's [a guide](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request) if you can't find the button but I'm sure you'll have no problem.

Frankly that's not all it takes. @itprdev you need to rebase your current branch to `develop` or create a new branch and cherrypick your existing commits into it. Now your PR also includes commits from `master` and can't be merged this way.

**Comment by ansuz** [comment]
I'm looking forward to seeing this land in master. When is the next release planned?

**Comment by Dunning-Kruger** [comment]
@ansuz Soon! Mentions of "this weekend" have been spotted in Slack but given the open-source nature of the project no commitments can be made.

**Pull request merged**
