### PR TITLE
Fix the flowchart syntax in the documentation

### PR DESCRIPTION
**Pull request by Mogztter**
## :bookmark_tabs: Summary

Otherwise the following exception is thrown:

```
Uncaught Error: Parse error on line 6:
...D --> B;    B ---->|No| E[End];
----------------------^
Expecting 'SPACE', 'GRAPH', 'DIR', 'subgraph', 'end', 'AMP', 'TAGEND', 'START_LINK', 'STR', 'STYLE', 'LINKSTYLE', 'CLASSDEF', 'CLASS', 'CLICK', 'DOWN', 'UP', 'DEFAULT', 'NUM', 'COMMA', 'ALPHA', 'COLON', 'MINUS', 'BRKT', 'DOT', 'PCT', 'TAGSTART', 'PUNCTUATION', 'UNICODE_TEXT', 'PLUS', 'EQUALS', 'MULT', 'UNDERSCORE', got 'PIPE'
    at Xt.parseError (flow.jison:293)
    at Xt.parse (flow.jison:363)
    at he (flowRenderer.js:285)
    at Object.render (mermaidAPI.js:331)
    at r.code ((index):47)
    at c.tok (docsify.min.js:1)
    at c.parse (docsify.min.js:1)
    at Function.c.parse [as parser] (docsify.min.js:1)
    at docsify.min.js:1
    at docsify.min.js:1
```

This exception prevents the page `/#/flowchart` from loading (i.e. blank page).
The error can be seen in the devtools console when running `docsify` locally from the `develop` branch.

## :straight_ruler: Design Decisions

Not sure if this is the right way to fix this issue.
Maybe it's a known limitation in the syntax? Maybe it's a bug in Mermaid and it should be possible to use `B ---->|No| E[End];`?

### :clipboard: Tasks
Make sure you
- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by GDFaber** [comment]
Hi @Mogztter, this is part of a new feature which was added in #1613. I think it should work locally but the live editor for mermaid 8.7.0 does not know the feature yet.

**Comment by Mogztter** [comment]
@GDFaber I'm not using the live editor but the documentation site (served by Docsify). As far as I know, the documentation site is already using 8.7.0: 

https://github.com/mermaid-js/mermaid/blob/7bb4f5591cbd2410feb7f9fe259e51f2ec85b611/docs/index.html#L10

Maybe this is an edge case and it's not supported by #1613?

**Comment by GDFaber** [comment]
Ah, I got it working on my local repository. mermaid 8.7.0 from npm is not aware of this new feature but the current develop branch can. I did the following things for it to work on the develop build which has the feature:

1. Change line 10 and 11 in docs/index.html as follows (this will render the diagrams using the develop build):
```
  <link rel="stylesheet" href="theme.css"> <!-- <script src="//cdn.jsdelivr.net/npm/mermaid@8.7.0/dist/mermaid.min.js"></script> -->
  <script src="http://localhost:9000/mermaid.js"></script>
```

2. Build mermaid.js and start the local dev server:
`yarn build`
`yarn dev`

After that, the flowchart examples should be visible via docsify.

**Comment by Mogztter** [comment]
Oh, I see... sorry about that!
I can confirm that this syntax is working using mermaid.js from the `develop` branch, closing.

**Pull request closed without merging**
