### PR TITLE
Fix typo in configuration.md

### LINKED ISSUE #1669: Minor : Typo in docs at assets/developer-docs/configuration
**Describe the bug**
In the `assets/developer-docs/configuration` doc, under `Theme configuration`->`Initialize`, *called* is wrongly spelled as *calloed*. 

**To Reproduce**
Go to [link](https://mermaid-js.github.io/mermaid/assets/developer-docs/configuration.html?highlight=theme).

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Lucurus**
## :bookmark_tabs: Summary
Fixed a typo in the docs (calloed to called).

Resolves #1669 

## :straight_ruler: Design Decisions
NA

### :clipboard: Tasks
Make sure you
- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md) 
- [ ] :computer: have added unit/e2e tests (if appropriate) 
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by saowang** [comment]
This file is not currently displayed in the list of documents

**Comment by Lucurus** [comment]
@saowang would you mind clarifying that as I'm not sure if I understood you correctly?

**Comment by NeilCuzon** [comment]
Good Day, @Lucurus, this document is not-and was not meant to be- part of the Docs, I appreciate the good intentions and I apologize for your confusion. 

I'll consider cleaning up the docs folder, so as to avoid further confusion. :) 

But I will have to close this PR.

**Comment by Lucurus** [comment]
Ahh ok no worries, thanks for the clarification!

**Pull request closed without merging**
