### PR TITLE
feat: expose the diagram api

### LINKED ISSUE #668: Has Mermaid a graphical interface to make diagrams?
Hi everybody!! Hope you're fine.
I love this project and I'm currently using it to make diagrams from text but I'm wondering if Mermaid has any mechanism to allow making diagrams with a graphical interface (like Visio or Draw for example).
If so, can you show me some example?
This feature is very useful but only I found the Mermaid editor which, as much as I understood, only shows what you input in text.
Thanks in advance.

Regards!

### LINKED ISSUE #4172: Expose the Diagram structure API
### Description

Hi,
I am building a graphical editor for mermaid js: www.mermaidflow.app/flowchart.

Users have expressed that they want to import mermaid js diagrams into it so that they can make edits visually and then reexport the diagram. To achieve this I would need to be able to parse the code and have an object returned that details the diagram structure. Currently the only api exposed is parse which returns a boolean but not quite the underlying Diagram.

Would you consider a new function that exposes this?

### Steps to reproduce

As above this is a feature request but didn't fall into the categories mentioned.

### Screenshots

_No response_

### Code Sample

```text
const diagram = parseDiagram(diagramCode);
// Diagram is an object the contains things like type as well as edges and nodes for the flowchart diagram for example.
```

### Setup

**Desktop**

- OS and Version: [Windows, Linux, Mac, ...]
- Browser and Version: [Chrome, Edge, Firefox]

**Smartphone**

- Device: [Samsung, iPhone, ...]
- OS and Version: [Android, iOS, ...]
- Browser and Version: [Chrome, Safari, ...]

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ted-marozzi**
## :bookmark_tabs: Summary

Brief description about the content of your PR.

Resolves #4172 and helps resolve #668, allowing me to create a graphical editor for mermaid flow (www.mermaidflow.app)
If you check out the site, you will see I have monkey patched your package allowing users to edit the UI or the code to produce a valid diagram.
## :straight_ruler: Design Decisions

Describe the way your implementation works or what design decisions you made if applicable.
Its very simple, I just expose the data structure needed to get diagram info.

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added unit/e2e tests (if appropriate)
- [x] :notebook: have added documentation (if appropriate)
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by ted-marozzi** [comment]
Hi maintainers, just want to get you opinion if its possible to expose this? If so I can add more to the documentation. This would be very useful and will help me solve issue #668 by creating a Graphical Mermaid Diagram Editor.
Thanks for the great ecosystem you have created!

**Comment by sidharthv96** [comment]
That's a wonderful app!
I don't see any major issue exposing this, apart from increasing the API surface area that we have to maintain.

**Review by sidharthv96 — APPROVED** [review]

**Comment by ted-marozzi** [comment]
Thanks for the review @sidharthv96, also may I ask what the process is for getting an app added to the integrations section?

**Review by aloisklink — COMMENTED** [review]
I'd like to first add some basic documentation to this function:

https://github.com/mermaid-js/mermaid/blob/ad52d7d823d3f8408d883f06937fe176c2128f37/packages/mermaid/src/Diagram.ts#L71

Ideally both it, and the `Diagram` type should have description, and a:

```typescript
/**
 * @privateRemarks This is exported as part of the public mermaidAPI.
 */
```

I'm also a bit reluctant to expose it publicly, since it adds a lot to the API surface. @sidharthv96, should we maybe mark this function as `@alpha` (see https://tsdoc.org/pages/tags/alpha/), and maybe stick a warning in the documentation that this API may change in future releases?

E.g. something like:

```typescript
/**
 * **Warning:** This function may be changed in the future.
 * @alpha
 */
```

**Comment by aloisklink** [comment]
> Thanks for the review, also may I ask what the process is for getting an app added to the integrations section?

Feel free to edit the integrations page yourself and make a PR: https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/ecosystem/integrations.md

We use a link-checker to make sure the URLs resolve, so make sure any links are stable!

There are instructions in https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md#committing-documentation on how to add documentation.

**Comment by ted-marozzi** [comment]
> I'd like to first add some basic documentation to this function:
> 
> https://github.com/mermaid-js/mermaid/blob/ad52d7d823d3f8408d883f06937fe176c2128f37/packages/mermaid/src/Diagram.ts#L71
> 
> Ideally both it, and the `Diagram` type should have description, and a:
> 
> ```ts
> /**
>  * @privateRemarks This is exported as part of the public mermaidAPI.
>  */
> ```
> 
> I'm also a bit reluctant to expose it publicly, since it adds a lot to the API surface. @sidharthv96, should we maybe mark this function as `@alpha` (see https://tsdoc.org/pages/tags/alpha/), and maybe stick a warning in the documentation that this API may change in future releases?
> 
> E.g. something like:
> 
> ```ts
> /**
>  * **Warning:** This function may be changed in the future.
>  * @alpha
>  */
> ```

Yep cool, alpha sounds like a good idea at least to start with. I will include some more documentation.

**Comment by ted-marozzi** [comment]
> > Thanks for the review, also may I ask what the process is for getting an app added to the integrations section?
> 
> Feel free to edit the integrations page yourself and make a PR: https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/ecosystem/integrations.md
> 
> We use a link-checker to make sure the URLs resolve, so make sure any links are stable!
> 
> There are instructions in https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md#committing-documentation on how to add documentation.

Thanks for this, I created pr #4184 :)

**Comment by ted-marozzi** [comment]
I added @alpha and @internal not sure if you wan't both or just one.

**Review by aloisklink — APPROVED** [review]
> I added alpha and internal not sure if you wan't both or just one.

To be honest, we only need one :)

`@alpha` is probably the one to go for, since we're making the API public on purpose, so that people can use it. But it's not too big of a deal to have both, I'm happy for this to be merged as it is.

**Comment by ted-marozzi** [comment]
> To be honest, we only need one :)
> 
> `@alpha` is probably the one to go for, since we're making the API public on purpose, so that people can use it. But it's not too big of a deal to have both, I'm happy for this to be merged as it is.

Easy to fix, I have left just alpha

**Pull request merged**
