### PR TITLE
Correct the System_Boundary stereotype

### PR DESCRIPTION
**Pull request by jonmcewen**
## :bookmark_tabs: Summary

Trivial change to correct the `[ENTERPRISE]` stereotype label to `[SYSTEM]` for C4 System_Boundary.

### CODE REVIEW

**Comment by sidharthv96** [comment]
@mermaid-js/atlantians can someone familiar with C4 review?

**Comment by jonmcewen** [comment]
> @mermaid-js/atlantians can someone familiar with C4 review?

 @mermaid-js/atlantians this should be a quick-win review for someone with a minute to spare please!

**Review by Yash-Singh1 — APPROVED** [review]
> @mermaid-js/atlantians can someone familiar with C4 review?

I haven't worked on the C4 Diagram, but this fixes the [example case](https://deploy-preview-5243--mermaid-js.netlify.app/edit#pako:eNqdVm1v2jAQ_isniw-tRBkEAi3aJvHWatIqdaWVtilS5SQHjZrYyDajrOp_n-PEJQlhfckXyOWee-78nM9-IgEPkQwJ6GfSm3Cm8FF5DMyjIhUjzLdSYQL5NwgjuhQ0gQUX8E2bBEMFY8oeIrbMfS1-ln5eiUji3ZivWUjF9shvN8Ejqb81tT1yDE8WA3CFQnJ2FKyl4gmKkfVP409yI4w8ktpHYN2AL0DdI_jaswmbSN3DygSisbEBDQJNqGRL0x0kG9eSjWsgd7NH9QKb1MImWY4hysAEOMg6rYVP_1_iZ198-vp6oTvSTJuj7GdklvWQfhlxHPONfGGXoDj8iXADEdPaJ1RFnAH1-VqlWUWizN4EykJI6APCim4TrEmotj061fbIu2MHs5VMfaNB9jJLYZdUp6Z7E2vrmSsuUAKNY7uQgTaYrFPX_apeKm8WqlKCMkmD1E2_oQqqVdn0CjU51ZqcSsvvy1PsiHwDjkpduAcZ10DGtoVk9v7mPQIs3epxxLBVYX2urXUnhNkKs5OERnHOmuVwo3kj026a7DIKBJd8oWD2GNxTtkTAIqRKagXPOaY1pU5hShX1qcSP1ryn407AblXAbkbil3t0X5sfa1xjnvV5TdbnYDwOp9w6ILqBFZb9oib4xWvB3zEnjfB7fwvNMI6uMS4O7eKcuZUoC-Ey351DYQtXPOv8TIfNkYUybxqZ7-_Lm6taqAaUDpMSVk-1kvC3q5AqnMWYjqy52sZYLKqx0KfghMdcfPGIwDBlbvhLa1kK3GYmLkJ9LBQdj8sMOr296LtKG-lRa-F-nInYSPfjnpEvFhLVT21yD5PUrPW7KX5p00mn_XaSyUdJeu1KZSfuq7RlkUu8VqcirbVVOEp5OO2azvhOt_ps0JehRbQ8agS9-T1d4Td2zTcaYcaCNtoxYe2dPJDHSJPoDHXnhfrSZUaGR_R2TPQaDNO7AhUPHvHYs_aja8XnWxaQoRJrbJK14Z9m1y8yXNBYauuKst-cJ9ZJv5LhE3kkwxO31T0buO3T047TdZ3eaa9Jttrc6Tutfrffd7rOYOD2B6fPTfLXROi03G57cOZ02v3eWX_guv3nf4YoQBc) in docs to have a system boundary labelled correctly on `BankBoundary2`. [Earlier](https://mermaid.live/edit#pako:eNqdVm1v2zgM_iuEkA8d4KZO4lza4O6AvG0YcAW2ZQW2wcAg20xi1JECSV6aFf3vo2W7sR3nus5fEtN8-JB6KEqPLJQRsjEDembeTAqDD8YXYB8TmwRhedAGt1B8gyjma8W3sJIK3pNJCTQw5eI-FuvCt8Qvss87FWv8PpWpiLg6XASuAz7L_EuT67M38FhiAD6g0lJchKk2cotqUvpn8WeFESY-y-wTKN1ArsBsEALydGAfmw3sbCCeWBvwMCRCo7tEd5Zs2ko2bYF8XzyYZ9isFTbLc4xQhzbAWdZ5K3z-_yX-Hairf18u9Eiaa3OR_0zssp7TLydOErnXz-wajIQfMe4hFqT9lptYCuCBTE2WVazq7A5wEcGW3yPs-GGLLQm1tkev2R5FdxxhZSXzwGqQvywy2C2n1Kg3sbWepZEKNfAkKRcyJIPNOnM9req5cqdSlVFcaB5mbvSGJmxWVaZXqanfrKnfaPlTeaodUWzASa0LTyDTFsi0bCGdv__2HgGRbfUkFthtsD611noUwm6FxeWWx0nBmufwmXhj225EdhuHSmq5MrB4CDdcrBGwCmmSloIXHPOWUucw54YHXOOf1nyi41HAQVPAQU4S1Hv0VJuPKaZYZP22Jeu3YD3Op9w9I7qFVZb9XUvwdy8Ff8WctMKf_K00wzT-hEl1aFfnzJ1GXQmX-x4dKlu44dnmZztsiSLSRdPoYn_ffv7QCiVA7TCpYWmq1YS_20Xc4CLBbGQtzSHBalGdFZ2CM5lI9Y_PFEYZcydYl5a1wkNukiqiY6Hq-KbOQOmdRD9W2smO2hIeJLmInWw_nhjlaqXRfCHT8DxJy1q_muIrmS577u-TzP6UxHMblV0OX6Sti1zjLXWq0pa2Bkctj77b0hn_8QOdDXQZWsXri07oLTd8h-_FJ7knhB0LZCzHRGnvFYF8wRxGGVLnRXTpsiPDZ7Qdt7QG4-yuwNW9z3zxRH48NXJ5ECEbG5Wiw1LLP8-vX2y84okm644LNn5kD2x82fO8rueNvJth73p47d24fYcdyD7w3O7AHbijzHTTH9389eSwn1JSkF73unc9GrnusOe6_aHb79uI3-zHnBajmA7O2_yaaG-LDqOVvKe3jTE7Pb662u_33TVNkjTohgR8-gU3ZlHX) it was labelled as enterprise boundary.

**Review by nirname — APPROVED** [review]

**Comment by nirname** [comment]
I haven't worked with C4 either, but this seems to be an obvious fix

**Pull request merged**
