### PR TITLE
Allow static/abstract classifier also for official UML syntax

### PR DESCRIPTION
**Pull request by skogsbaer**
## :bookmark_tabs: Summary

Previously, the static classifier was only supported for attributes using the syntax `String name$`. Now you can also write `name: String$`

Further, it was confusing that static/abstract classifiers for methods had to be written after the closing parenthesis of the method signature, even if the method has a return type. So you had to write `foo(name: String)* int`.

This commit also adds the possibility of writing the classifier at the
very end, as in `foo(name: String) int*`.

 See PR #2269 and issue #3001 and my old issue #1953

## :straight_ruler: Design Decisions

No real design desicions had to be made. I added new unit tests and made sure that all old tests are running.

### :clipboard: Tasks

Make sure you

- [ x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x ] :computer: have added unit/e2e tests (if appropriate)
- [x ] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by skogsbaer** [comment]
I'm happy to fix the conflicts, but I suggest a review first.

**Review by ashishjain0512 — CHANGES_REQUESTED** [review]
@skogsbaer Great work; it adds to our efforts in making class diagrams more aligned with official UML syntax. The changes look good. I would request to add a few rendering test cases  @ cypress/integration/rendering/classDiagram-v2.spec.js

This will ensure we have proper snapshot test cases for the added new stuff.  Once we have those, we will be happy to merge.

**Comment by skogsbaer** [comment]
@ashishjain0512 I tried adding the tests but it seems that some of them are broken. For example, test 19 in `cypress/integration/rendering/classDiagram.spec.js` has a syntax error, although I did not change anything:

screenshot

**Comment by jgreywolf** [comment]
I am closing this since the changes were included in PR #4303

**Pull request closed without merging**
