### PR TITLE
Fix Twitter fontawesome class in flowchart.md

### PR DESCRIPTION
**Pull request by GingerNinjaNicko**
## :bookmark_tabs: Summary

Fixes a typo in fontawesome class

## :straight_ruler: Design Decisions

fixes simple typo - not a feature

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added necessary unit/e2e tests.
- [x] :notebook: have added documentation. Make sure [`MERMAID_RELEASE_VERSION`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/docs/community/development.md#3-update-documentation) is used for all new features.
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by Yokozuna59** [comment]
@sidharthv96 The PR author changed the `packages/mermaid/src/docs/` without `docs/`.

**Comment by sidharthv96** [comment]
We have a workflow that will push the built docs to develop. 

So minimal changes like this can be merged without bothering the authors.

**Comment by Yokozuna59** [comment]
Then we should do something about gh actions that will fail on each push.

**Comment by sidharthv96** [comment]
image
 
It seems like that flow is broken now. 

> Then we should do something about gh actions that will fail on each push.

We cannot push to forks, so we cannot update the PR branch, unless we add a PAT, which is very insecure.

**Pull request merged**
