### PR TITLE
Initial implementation for Issue#2249.

### PR DESCRIPTION
**Pull request by eajenkins**
Includes changes to sequence diagram code to enable popup menus and individualized styling of actors
Includes unit and e2e tests.
Includes updates to the md file for sequencediagrams.

## :bookmark_tabs: Summary
Brief description about the content of your PR.

Resolves #<your issue id here>

## :straight_ruler: Design Decisions
Describe the way your implementation works or what design decisions you made if applicable.

### :clipboard: Tasks
Make sure you
- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md) 
- [x] :computer: have added unit/e2e tests (if appropriate) 
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by knsv** [comment]
I supplied some comments, are this PR still active?

**Comment by elgalu** [comment]
This looks awesome! thanks! I think with the addition of `properties_statement` also partially address #2314 <3

**Comment by knsv** [comment]
Merging. Good job! Great to see all parts in place with boths tests, renderings tests and documentation. And a great feature!

**Comment by knsv** [comment]
There will probably be changes regarding the class handling. I want to have a way of doing this that can be applied to all diagram types as a normalization step.

**Pull request merged**
