### PR TITLE
Expose `registerDiagram()` for non-lazyLoadedDiagrams

### LINKED ISSUE #3701: Bundling external diagrams
**Is your feature request related to a problem? Please describe.**
With the new lazyLoadedDiagrams, there is the requirement for an extra web request to fetch diagrams.
This might not be feasible in all environments (corporate firewalls, plugin limitations, etc).

**Describe the solution you'd like**
We should allow an option to pass diagrams directly to mermaid so it can avoid the network call. 
This way, external diagrams could be bundled in at build time (if needed), reducing the time to load.

**Describe alternatives you've considered**
None

**Additional context**
We could also release versions of mermaid with different diagrams bundled.

### PR DESCRIPTION
**Pull request by aloisklink**
## :bookmark_tabs: Summary

Exposes the `registerDiagram()` function publicly as `mermaid.mermaidAPI.registerDiagram` so that users can add their own diagrams at bundle-time.

This is instead of using the `lazyLoadedDiagrams` config setting.

Resolves #3701

## :straight_ruler: Design Decisions

In order to get this working, I updated `@mermaid-js/mermaid-mindmap` so that you can now get both the `id` and `detector` by running `import("@mermaid-js/mermaid-mindmap")`.

### Example usage

```js
import {
  diagram as mindmap,
  detector as mindmapDetector,
  id as mindmapId,
} from '@mermaid-js/mermaid-mindmap';
import {
  diagram as exampleDiagram,
  detector as exampleDiagramDetector,
  id as exampleDiagramId,
} from '@mermaid-js/mermaid-example-diagram';
import mermaid from 'mermaid';

mermaid.mermaidAPI.registerDiagram(mindmapId, mindmap, mindmapDetector);
mermaid.mermaidAPI.registerDiagram(exampleDiagramId, exampleDiagram, exampleDiagramDetector);
await mermaid.initialize({ logLevel: 0 });
await mermaid.initThrowsErrors();
```

Also, to make life slightly easier, `registerDiagram` no longer takes a callback. Instead, it checks whether the diagram contains an `injectUtils` function, and if it does, it uses that as the callback instead.

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added unit/e2e tests (if appropriate)
- [x] :bookmark: targeted `develop` branch
  - This PR also merges cleanly with the `release_9.2.0_buggfixes` branch, in case we want to back-port this to v9.2.0 as well.

### CODE REVIEW

**Review by knsv — APPROVED** [review]
Nice work!

**Comment by sidharthv96** [comment]
Incorporated in https://github.com/mermaid-js/mermaid/pull/3774

**Comment by Billiam** [comment]
@sidharthv96  It seems like the change to actually export `registerDiagram` (https://github.com/mermaid-js/mermaid/pull/3710/files#diff-8f9cbf877a7595ee65c9cb40cbfd22234c40531a90ecccf1bb33c6ae0432edf1R484-R491) didn't make it in.

The spec for `registerDiagram` (using `external-diagrams-mindmap.html`) _was_ added, but the html file is still using the original `registerExternalDiagrams` method instead: https://github.com/mermaid-js/mermaid/blob/master/cypress/platform/external-diagrams-mindmap.html#L44

Possibly failed conflict resolution?

**Comment by sidharthv96** [comment]
@Billiam It was a [deliberate choice](https://github.com/mermaid-js/mermaid/pull/3774#discussion_r1017418307) not to export `registerDiagram`. `registerExternalDiagrams` was added to support the functionality.

**Comment by Billiam** [comment]
Thanks! Sorry I missed that discussion

**Pull request closed without merging**
