### PR TITLE
Working New Documentation Vitepress

### PR DESCRIPTION
**Pull request by emersonbottero**
## :bookmark_tabs: Summary

Brief description about the content of your PR.

## :straight_ruler: Design Decisions

Describe the way your implementation works or what design decisions you made if applicable.

Key points:

- All new docs reside in vdocs folder
- uninstalled documentation lib (vue versions incompatible)
  (resolves https://github.com/mermaid-js/mermaid/issues/3351)
- how to build the docs
  - yarn build (it will throw erros but it will create the dis folder)
  - yarn vdocs:build
  - yarn vdocs:serve
- I changed how the fontawesome example works (it will look strange in the github version)
- the dev mod for now does not work.. I'll try to contact vitepress team.
- removed search for now (Still have to change the build first)
- pipeline to publish in github paes [here](https://github.com/emersonbottero/mermaid-docs/blob/main/.github/workflows/gh-pages-publish.yml)
see #3484 

### :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid/blob/develop/CONTRIBUTING.md)
- [x] :computer: have added unit/e2e tests (if appropriate)
- [x] :bookmark: targeted `develop` branch

### CODE REVIEW

**Comment by emersonbottero** [comment]
Fixed the search plugin 🎉

In the end of the theming documentation page the base theme looked bad in dark theme (it does make sense)
then I tried to changed it to neutral.. but it still the arrows and texts seems wrong.. 

image

**Comment by knsv** [comment]
This looks very promising. Smart to put it in parallel with current docs to start with. @emersonbottero I was about to merge this but there is a conflict in the scripts part in package.json. Could you align this with develop? Then I will merge! Also a hedas up, we are turning Mermaid into a monorepo, you can take a sneak peak at 3061_making_a_monorepo. At some point I will merge it (to avoid more conflicts) and pick up the pieces later.

**Comment by emersonbottero** [comment]
@knsv Done.

**Comment by knsv** [comment]
Thanks!

**Pull request merged**
